Procfile
config/createDatabase.ts
views/assets/css/dashboard.css
views/dashboard/api-authentications-connect.ejs

Fix an issue with the deploy to heroku (due to new package scripts naming). Also improved a little bit the "Connect" from the dashboard flow, by providing the right callback URL to use.

Fix heroku deployment

---

app.json

I have removed most of the environment variables in `app.json` to reduce the friction when deploying to heroku.

feat: reduce the amount of environment for Heroku

---

README.md

Added a few clarity updates to the readme.

Update language in readme

---

integrations/quickbooks-sandbox.json
integrations/revolut-sandbox.json
src/lib/database/integrations.ts

Replace http with https for clearbit.com url

replace http with https for clearbit.com url

---

integrations/discord.json

Fixing the discord configuration file. It's preferrable to not have a link to the repo nore Pizzly version in the user-agent.
What types of changes does your code introduce to Appium?

fix: remove project link + version

---

integrations/zendesk-chat.json

The Zendesk configuration file was not properly set. A dynamic params `domain` required for the OAuth-dance was missing. This PR attempts to fix this.

fix: Update Zendesk Chat configuration file

---

src/index.ts

Sets the `Strict-Transport-Security` header which tells browsers to prefer HTTPS over insecure HTTP. See [the documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) for more.
We might consider adding [Helmet](https://github.com/helmetjs/helmet) in the near future.

feat: add HSTS header

---

views/dashboard/api-authentications-connect.ejs
views/dashboard/api-authentications-item.ejs
views/dashboard/api-request.ejs

Added a link "Try it now" when using the Connect button in Pizzly's dashboard. To make it easier to try an integration.

feat: add a try this authId link

---

README.md
docs/API.md
docs/auth.md
docs/dashboard.md
docs/examples.md
docs/getting-started.md
docs/integrations.md
docs/proxy.md
docs/readme.md
docs/securing-your-instance.md
docs/supported-apis.md
docs/telemetry.md
src/clients/javascript/README.md

Documentation currently exists in the wiki, which limits our ability to open it up to the community and limits what we can do (in terms of automation, front-facing docs, etc). This PR starts the process of migrating the docs over to the main repo.

Start transition of docs

---

views/dashboard/settings-keys.ejs

Fixed a bug where in the Dashboard settings page, the link to the "Secure Your Instance" docs was using the old page location.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Bugfix: Updated link to "Secure Your Instance" docs in Dashboard

---

app.json

Resolves #192 where heroku setup no longer works

Add pgsslmode config env

---

integrations/zoho-crm.json
integrations/zoho-subscriptions.json

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
- [ x] Bugfix (non-breaking change which fixes an issue)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

- added the correct authorization for zoho crm and subscriptions.

---

docs/API.md
src/clients/node/examples/index.js
src/clients/node/src/api.ts
src/clients/node/src/index.ts
src/clients/node/src/utils.ts
src/clients/node/test/api.test.ts

Hey guys!
closes #190 
I would like to introduce the api part of the Nodejs client.
With the NodeJs client, you can know get access to the API of Pizzly.
```TypeScript
const pizzly = new Pizzly({ host: 'example.org', secretKey: 'myKey' })
const apiClient = pizzly.api('google-drive')
// Manage configuration through API
await apiClient.get('configurations')
await apiClient.put('configurations/72184458-7751-41fe-8dcc-0251ab2cc578', {
body: { credentials: { clientId: 'abcd***************', clientSecret: '1234***********************' } }
})
await apiClient.delete('configurations/72184458-7751-41fe-8dcc-0251ab2cc578')
// Manage Authentifications through API
await apiClient.get('authentifications')
await apiClient.post('authentifications/1994cc00-a4d6-11ea-9187-b798bad9d2ac/refresh')
await …
```

API client for Nodejs client

---

.github/workflows/publish-container-image.yaml
Dockerfile
package.json

Publish a container image to GitHub's container registry
NA

feat: add automation to publish container image

---

docs/getting-started.md

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
- [x ] I have read the [CONTRIBUTING](https://github.com/bearer/pizzly/blob/master/README.md#contributing-guide) guide
- [ x] I have added necessary documentation (if appropriate)
If this is a relatively large or complex change, kick off the …

Trivial documentation fix

---

.env
package-lock.json
packages/cli/lib/index.ts
packages/frontend/lib/index.ts
packages/node-client/bin/examples.js
packages/node-client/lib/index.ts
packages/server/lib/access.middleware.ts
packages/server/lib/config.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/server.ts
packages/server/lib/utils/logger.ts
packages/server/package.json

- Secure with secret + publishable keys (close #271 )
- Fix Node SDK for OAuth 1 (close #276)

Secure Pizzly request + fix OAuth 1 in SDK

---

docker-compose.yaml
package-lock.json
package.json
packages/auth/lib/auth.server.ts
packages/auth/lib/controllers/connection.controller.ts
packages/auth/lib/controllers/oauth.controller.ts
packages/auth/lib/db/knexfile.cjs
packages/auth/lib/db/migrations/20221026075018_create_connection.cjs
packages/auth/lib/db/migrations/20221026075019_create_config.cjs
packages/auth/lib/db/migrations/20221223094334_add_connection_config.cjs
packages/auth/lib/models.ts
packages/auth/lib/oauth-clients/oauth2.client.ts
packages/auth/lib/services/connection.service.ts
packages/auth/lib/utils/utils.ts
packages/auth/package.json
packages/auth/providers.yaml
packages/cli/lib/index.ts
packages/cli/package.json
packages/frontend/lib/index.ts
packages/frontend/package.json
packages/node-client/lib/index.ts
packages/node-client/package.json
packages/server/package.json

- Add auth/token url string interpolation + Zendesk (close #290 , 
- Only snake case field in credentials response (close #284, close #286)
- Patch

Add Zendesk + initial templating

---

README.md
docs/docs/nango-deploy/render.md
docs/sidebars.js
render.yaml

docs: Add a one-click deploy to render button

---

docs/docs/providers/calendly.md
docs/sidebars.js
packages/server/providers.yaml

I tested the full flow, I was able to get access & refresh token without any issues.

Add calendly API provider

---

packages/webapp/src/components/AlertOverLay.tsx
packages/webapp/src/pages/IntegrationCreate.tsx

**Description**
This is a PR to the issue [here](https://github.com/NangoHQ/nango/issues/368)
Image.

feat: Dashboard: Confirmation before delete

---

packages/server/lib/server.ts
packages/server/lib/utils/utils.ts

What the PR does
This PR adds the current node version to the logs when the server connects, the server uses the package.json to know the current version.
Issue PR solves
This PR solves the issue https://github.com/NangoHQ/nango/issues/374

refactor: 💡 add server version in server ts 

---

.husky/pre-commit
package-lock.json
package.json
packages/server/Dockerfile
packages/webapp/src/reportWebVitals.ts

**Description**
This PR allows us to add a precommit hook to help format based on the prettierc. It will help us standardize the format so that formats will not vary.

ci: added precommit hook

---

docs/docs/providers/strava.md
docs/sidebars.js
packages/server/providers.yaml

This PR adds integration for Strava based on the issue [here](https://github.com/NangoHQ/nango/issues/405)

feat: Add Strava provider

---

docs/docs/providers/asana.md
packages/server/providers.yaml

This fixes the issue [here](https://github.com/NangoHQ/nango/issues/455)

fix: Asana Integrations

---

docs/docs/providers/figma.md
docs/sidebars.js
packages/server/lib/clients/provider.client.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/oauth.controller.ts
packages/server/lib/models.ts
packages/server/lib/services/connection.service.ts
packages/server/providers.yaml

**Description** 
This PR adds figma as a provider, Figma uses a query param type of authentication hence, I have created a custom authorization and request token for the provider.
PS: My weirdest integration 😄

Feat: Add Figma Provider

---

docs/docs/providers/miro.md
docs/sidebars.js
packages/server/providers.yaml

**Description**
This PR adds a provider for Miro.
[Issue](https://github.com/NangoHQ/nango/issues/444)

fix:Added Provider for Miro.

---

docs/docs/providers/gusto.md
docs/sidebars.js
packages/server/providers.yaml

Please see [here](https://github.com/NangoHQ/nango/issues/417)

Feat: Add provider for Gusto.

---

packages/webapp/src/pages/ConnectionCreate.tsx

**Description** 
I was carrying out a QA of Nango and I noticed it.
This PR fixes the issue

fix: Connection create page

---

docs/docs/providers/typeform.md
docs/sidebars.js
packages/server/providers.yaml

[Issue](https://github.com/NangoHQ/nango/issues/414)

feat: Add provider for typeform

---

docs/docs/providers/gorgias.md
docs/sidebars.js
packages/server/lib/clients/oauth2.client.ts
packages/server/providers.yaml

[Issue](https://github.com/NangoHQ/nango/issues/439)

feat: Add provider for Gorgias

---

docs/docs/quickstart.md

Noticed a typo while going through quickstart.

docs: fix typo

---

package-lock.json
packages/frontend/lib/index.ts
packages/frontend/package.json
packages/server/package.json
packages/webapp/package.json

Fix Safari popup blocker

---

packages/server/lib/controllers/account.controller.ts
packages/server/lib/controllers/auth.controller.ts
packages/server/lib/controllers/config.controller.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/user.controller.ts
packages/server/lib/utils/utils.ts

Fix spelling error from Sesstion to Session wherever used

getUserAndAccountFromSesstion -> getUserAndAccountFromSession

---

docs/docs/providers/todoist.md
docs/sidebars.js
packages/server/providers.yaml

Add the OAuth2 configuration to create a [Todoist](https://todoist.com) API integration.

Add Todoist API provider

---

package-lock.json
packages/webapp/src/components/ui/SecretInput.tsx
packages/webapp/src/components/ui/button/CopyButton.tsx
packages/webapp/src/pages/IntegrationCreate.tsx

Firstly apologies @bastienbeurier, There were some missing code throughout these consecutive PR's and merges in `IntegrationCreate.tsx` this is hotfix PR to clear them all at once.
also in this same PR I have incorporated `CopyButton.tsx`  in `SecretInput.tsx` which allows user to copy the text.

feat: add copy option to secret button and adds "missing code"

---

packages/server/lib/db/db.config.ts

support for configuring different types of database clients.

Feat: add client type env to support cockroachdb

---

packages/webapp/src/pages/ProjectSettings.tsx

protect secret key

---

packages/server/lib/utils/utils.ts

Fix undefined server version log

---

packages/server/lib/controllers/account.controller.ts
packages/server/lib/models.ts
packages/webapp/src/pages/ConnectionCreate.tsx

Fix frontend snippet (self-hosted)

---

packages/webapp/src/pages/Signin.tsx
packages/webapp/src/pages/Signup.tsx

Add privacy and terms to login/signup

---

packages/webapp/src/pages/IntegrationCreate.tsx

Support integration with no scope

---

package-lock.json
packages/frontend/package.json

Revert frontend build script

---

.github/workflows/build.yaml
.github/workflows/docker.yaml
.github/workflows/validation.yaml

[gh-#620] add pull_request action

---

packages/node-client/lib/index.ts

[gh-#628] use custom headers

---

packages/webapp/src/components/Banner.tsx
packages/webapp/src/components/TopNavBar.tsx
packages/webapp/src/utils/local-storage.tsx

Nango Sync banner

---

docker-compose.yaml
docs-v2/contribute/nango-auth.mdx
package-lock.json
packages/server/package.json
packages/shared/package.json

[Github #652] fix container mapping

---

packages/node-client/bin/list-connections.js
packages/node-client/lib/index.ts
packages/node-client/package.json

[gh-#654] resolve connectionId not being honored

---

packages/server/lib/utils/error.ts
packages/shared/providers.yaml

Resolves #659 
Adds additional proxy providers
* hubspot
* airtable
* asana
* slack

[Github #659] proxy update

---

packages/node-client/lib/index.ts
packages/node-client/lib/types.ts
packages/server/lib/controllers/proxy.controller.ts

[Github #662] fix proxy params

---

.env.example
docker-compose.yaml
packages/shared/lib/utils/encryption.manager.ts

[Github #682] env fix

---

docker-compose.yaml
package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/lib/sync.ts
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/integration.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json
scripts/release.bash

[gh-#694] use secret key as env

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/lib/sync.ts
packages/cli/lib/utils.ts
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/lib/server.ts
packages/server/package.json
packages/shared/lib/services/config.service.ts
packages/shared/lib/services/file.service.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

* Bump entity size
* Delete files if a provider config is deleted
* Add `NANGO_NO_PROMPT_FOR_UPGRADE`

[Gh #692] request entity update

---

package-lock.json
package.json
packages/cli/docker/docker-compose.yaml
packages/cli/lib/index.ts
packages/cli/lib/sync.ts
packages/cli/lib/utils.ts
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/utils/encryption.manager.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json
scripts/release.bash
tsconfig.build.json

[gh-#701] add getNangoRootPath

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/lib/index.ts
packages/cli/lib/sync.ts
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/sdk/sync.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

[gh-#704] use underlying nango call for connection

---

.github/workflows/docker.yaml
package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/webapp/src/pages/ConnectionDetails.tsx
packages/worker/lib/activities.ts
packages/worker/package.json

Gh #713 fix sync button

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/db/migrations/20230703041405_update_sync_models.cjs
packages/shared/lib/models/Sync.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/nango-config.service.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/lib/services/sync/orchestrator.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/sync/sync.service.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/webapp/src/pages/ConnectionDetails.tsx
packages/webapp/src/pages/Syncs.tsx
packages/webapp/src/types.ts
packages/worker/package.json

Resolves #724 
* Handles connections properly
* Updates schedules for all connections properly
* Updates the sync model with some documentation in the sync.service
* Adds version to the sync in the ConnectionDetails and Syncs tab

[gh-#724] model fixes and updates

---

packages/webapp/src/App.tsx
packages/webapp/src/pages/AuthLink.tsx

[gh-#603] MVP for triggering auth with a link

---

.github/workflows/docker.yaml
README.md
docs-v2/contribute.mdx
docs-v2/guides/oauth.mdx
docs-v2/guides/sync.mdx
docs-v2/quickstart.mdx
docs-v2/sdks/cli.mdx
package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/lib/utils.ts
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

[gh-#721] nango globally

---

docs-v2/examples/slack-users.mdx
docs-v2/guides/sync.mdx
package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/webapp/src/pages/ConnectionDetails.tsx
packages/webapp/src/pages/Syncs.tsx
packages/webapp/src/utils/utils.tsx
packages/worker/package.json

[gh-#742] fix sync docs link

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/lib/sync.ts
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

[Github #745] remove asana

---

docs-v2/guides/sync.mdx

[gh-#722] fix typo and add note about model

---

packages/shared/lib/services/sync/run.service.test.ts
packages/shared/lib/services/sync/run.service.ts
packages/webapp/src/pages/ConnectionDetails.tsx
packages/webapp/src/utils/utils.tsx
packages/worker/lib/activities.ts

[Github #720] next sync time

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/services/environment.service.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

[gh-#781] Add environment to the cache, not the encrypted environment

---

packages/cli/lib/sync.ts
packages/shared/lib/services/sync/config.service.ts

Resolves #729 
- Remaining issue that if the syncs were not deployed yet it still confirms that they were deleted even nothing actually happened since there wasn't anything to delete

[Github-#729] allow deleting all syncs

---

packages/server/lib/controllers/access.middleware.ts
packages/server/lib/controllers/auth.controller.ts
packages/server/lib/controllers/config.controller.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/proxy.controller.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/services/account.service.ts
packages/shared/lib/services/activity.service.ts
packages/shared/lib/services/connection.service.ts
packages/shared/lib/services/environment.service.ts
packages/shared/lib/services/file.service.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/sync/schedule.service.ts
packages/shared/lib/utils/analytics.ts
packages/shared/lib/utils/error.manager.ts
packages/shared/lib/utils/error.ts

Gh #783 improve error handling

---

packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/models/Activity.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/sync/sync.service.ts
packages/webapp/src/components/ui/button/CopyButton.tsx
packages/webapp/src/pages/Activity.tsx
packages/webapp/src/types.ts

Resolves #716 
Resolves #766 
Resolves #715

[Github #716] sync button & other improvements

---

packages/node-client/bin/proxy.js
packages/server/lib/controllers/oauth.controller.ts
packages/server/lib/utils/web-socket-error.ts

Gh #750 full error

---

packages/cli/lib/utils.ts
packages/cli/package.json

Gh #788 windows compat

---

packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/lib/services/sync/orchestrator.service.ts
packages/shared/lib/services/sync/sync.service.ts

[gh-#791] handle dupe syncs by forcing user to report the error

---

packages/cli/lib/utils.ts

Fixes issues mentioned in the community:
- https://nango-community.slack.com/archives/C051VRNQVJM/p1690097994975229
- https://nango-community.slack.com/archives/C04ABR352H0/p1689444388625649?thread_ts=1689444267.583329&cid=C04ABR352H0

[gh-#811] run generate as an option if not existing

---

packages/frontend/lib/index.ts
packages/server/lib/controllers/apiAuth.controller.ts
packages/server/lib/controllers/proxy.controller.test.ts
packages/server/lib/controllers/proxy.controller.ts
packages/webapp/src/pages/ConnectionCreate.tsx
packages/webapp/tsconfig.json

[Github #820] password optional

---

packages/server/lib/controllers/activity.controller.ts
packages/server/lib/jobs/index.ts
packages/server/lib/server.ts
packages/shared/lib/db/migrations/20230725102233_unique_sync_name_per_connection.cjs
packages/shared/lib/db/migrations/20230725103142_activity_indices.cjs
packages/shared/lib/services/activity/activity.service.ts
packages/webapp/src/pages/Activity.tsx

[gh-#791] remove job script and quick activity page improvements

---

packages/server/lib/controllers/apiAuth.controller.ts
packages/server/lib/controllers/oauth.controller.ts
packages/server/lib/utils/utils.ts
packages/shared/lib/utils/utils.ts
packages/webapp/src/pages/ConnectionDetails.tsx

[gh-#822] connection config for providers with dynamic properties

---

packages/webapp/src/components/LeftNavBar.tsx
packages/webapp/src/layout/DashboardLayout.tsx
packages/webapp/src/pages/ConnectionDetails.tsx
packages/webapp/src/pages/IntegrationCreate.tsx

[Github #769] env dropdown improvements

---

packages/webapp/src/pages/ConnectionCreate.tsx
packages/webapp/src/pages/IntegrationCreate.tsx

[gh-#838] fix object and update styling

---

packages/server/lib/jobs/index.ts
packages/server/lib/server.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/index.ts
packages/shared/lib/services/config.service.ts
packages/shared/lib/services/connection.service.ts
packages/shared/lib/services/sync/orchestrator.service.ts
packages/shared/lib/services/sync/schedule.service.ts

Resolves #847 
See description on the issue.

[Github #847] delete syncs correctly

---

packages/node-client/lib/index.ts
packages/shared/lib/sdk/sync.ts

[gh-#366] update set field mapping type

---

packages/shared/lib/db/migrations/20230727075437_scopes_length.cjs

[gh-#852] scopes migration

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/data-records.service.ts
packages/shared/lib/services/sync/data.service.ts
packages/shared/lib/utils/error.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

Gh #801 batch send

---

packages/cli/lib/sync.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/db/migrations/20230728114040_last_sync_date.cjs
packages/shared/lib/models/Sync.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/sync/sync.service.ts
packages/shared/lib/utils/error.manager.ts

Resolves #752 
Also fixes sentry errors coming in as anonymous

[Github #752] last sync date

---

packages/server/lib/controllers/config.controller.integration.test.ts
packages/shared/lib/db/ db.integration.test.ts
packages/shared/lib/db/database.ts
packages/shared/lib/db/db.integration.test.ts
packages/shared/lib/db/seeders/config.seeder.ts
packages/shared/lib/db/seeders/connection.seeder.ts
packages/shared/lib/db/seeders/sync-job.seeder.ts
packages/shared/lib/db/seeders/sync.seeder.ts
packages/shared/lib/services/sync/data-records.service.ts
packages/shared/lib/services/sync/data.service.integration.test.ts
packages/shared/lib/services/sync/data.service.ts
packages/shared/lib/services/sync/data.service.unit.test.ts

[Github #865] improve on conflict issue

---

packages/shared/lib/clients/sync.client.ts
packages/shared/lib/db/migrations/20230803113912_remove_activity_log.cjs
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/sync/job.service.ts
packages/worker/lib/activities.ts

[gh-#869] remove activity log id from jobs table

---

packages/shared/lib/utils/utils.ts

[gh-#866] fix baseUrl

---

packages/cli/lib/sync.ts

[gh-#867] compile before dry run

---

packages/node-client/bin/get-records.js
packages/node-client/lib/index.ts
packages/node-client/lib/types.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/services/sync/data-records.service.ts

[gh-#842] add sortBy and order

---

packages/webapp/src/pages/ConnectionDetails.tsx
packages/webapp/src/pages/IntegrationCreate.tsx
packages/webapp/src/utils/api.tsx

[gh-#877] expect a 204

---

docs-v2/sdks/node.mdx
docs-v2/spec.yaml

[gh-#875] docs update

---

packages/shared/lib/clients/provider.client.ts

Fixes sentry error: https://nango.sentry.io/issues/4378523162/?alert_rule_id=13812048&alert_type=issue&project=4504688963682304&referrer=slack

[gh-#874] use connection_config

---

packages/server/lib/controllers/proxy.controller.ts

[gh-#887] retry on connection reset

---

docs-v2/api-reference/sync/records-get.mdx
docs-v2/sdks/node.mdx
docs-v2/spec.yaml
packages/node-client/bin/get-records.js
packages/node-client/lib/index.ts
packages/node-client/lib/types.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/services/sync/data-records.service.ts

[gh-#893] include_nango_metadata

---

packages/shared/lib/clients/sync.client.ts

[gh-#896] overlap policy

---

packages/server/lib/controllers/proxy.controller.ts
packages/shared/lib/index.ts
packages/shared/lib/services/sync/job.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/providers.yaml
packages/worker/lib/activities.ts

[gh-#896] check db for an existing initial sync

---

packages/cli/lib/sync.ts
packages/cli/lib/utils.ts

[gh-#902] dont require id on aux models

---

packages/server/lib/utils/utils.ts
packages/shared/lib/clients/oauth2.client.ts

[gh-#908] remove connectionConfig

---

packages/server/lib/controllers/proxy.controller.ts

[gh-#907] ETIMEDOUT and ECONNABORTED

---

integration-templates/confluence/confluence-pages.ts
integration-templates/confluence/confluence-spaces.ts
integration-templates/confluence/nango.yaml

New Integration Templates - Confluence Spaces & Pages

---

docs-v2/integration-templates/confluence.mdx
docs-v2/integration-templates/hubspot.mdx
docs-v2/mint.json
integration-templates/asana/asana-tasks.ts
integration-templates/confluence/confluence-spaces.ts
integration-templates/github/github-issues.ts
integration-templates/gmail/gmail-emails.ts
integration-templates/google-workspace/google-workspace-user-access-tokens.ts
integration-templates/hubspot/hubspot-service-tickets.ts
integration-templates/intercom/intercom-contacts.ts
integration-templates/intercom/intercom-conversations.ts
integration-templates/jira/jira-issues.ts
integration-templates/linear/linear-projects.ts
integration-templates/linear/linear-roadmaps.ts
integration-templates/linear/linear-teams.ts
integration-templates/notion/notion-pages.ts
integration-templates/salesforce/salesforce-accounts.ts
integration-templates/salesforce/salesforce-contacts.ts
integration-templates/slack/slack-channels.ts
integration-templates/slack/slack-messages.ts
integration-templates/slack/slack-users.ts

- Patch template return statements
- Add Hubspot and Confluence templates to docs
Resolves #934 
Resolves #933

Patch templates + add Confluence/Hubspot

---

packages/node-client/lib/types.ts
packages/shared/lib/sdk/sync.ts
packages/webapp/src/types.ts

Fix node field mapping compilation error

---

docs-v2/integrations/all/evaluagent.mdx
docs-v2/mint.json
integration-templates/evaluagent/evaluagent-groups.ts
integration-templates/evaluagent/evaluagent-roles.ts
integration-templates/evaluagent/evaluagent-users.ts
integration-templates/evaluagent/nango.yaml
packages/shared/providers.yaml

Integration with the EvaluAgent API including syncs with Users, Groups and Roles endpoints.

Integration - EvaluAgent API

---

packages/shared/lib/services/connection.service.ts

Fix import bug related to metadata

---

packages/cli/lib/index.ts
packages/cli/lib/sync.ts
packages/node-client/bin/action.js
packages/node-client/lib/index.ts
packages/server/lib/controllers/sync.controller.ts
packages/server/lib/server.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/db/migrations/20230904183820_add_action_type.cjs
packages/shared/lib/integrations/index.ts
packages/shared/lib/models/Activity.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/nango-config.service.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/lib/services/sync/config.service.unit.test.ts
packages/shared/lib/services/sync/integration.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/sync/sync.service.ts
packages/webapp/src/pages/Activity.tsx
packages/webapp/src/pages/Syncs.tsx
packages/webapp/src/types.ts
packages/worker/lib/activities.ts
packages/worker/lib/models/Worker.ts
packages/worker/lib/workflows.ts

[Github #962] actions

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json
scripts/release.bash

[Github #968] build commonjs sdk

---

docs-v2/integrations/all/aircall.mdx
docs-v2/integrations/all/servicem8.mdx
docs-v2/mint.json
packages/shared/providers.yaml

Both integrations tested OAuth flows successfully

Add Aircall.io + ServiceM8 Integrations

---

packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/webhook.service.ts

[gh-#979] send webhook for deletes as well

---

packages/cli/lib/action.ejs
packages/cli/lib/github.sync.ejs
packages/cli/lib/index.ts
packages/cli/lib/integration.ejs
packages/cli/lib/sync.ejs
packages/cli/lib/sync.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/config.service.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/lib/services/sync/config.service.unit.test.ts
packages/shared/lib/services/sync/sync.service.ts
packages/webapp/package-lock.json
packages/webapp/package.json
packages/webapp/src/components/LeftNavBar.tsx
packages/webapp/src/pages/Activity.tsx
packages/webapp/src/pages/Syncs.tsx

[Github #973] action polish

---

package-lock.json
packages/shared/lib/index.ts
packages/shared/lib/services/connection.service.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/error.manager.ts
packages/shared/lib/utils/metrics.manager.ts
packages/shared/package.json
packages/worker/lib/activities.ts

[gh-#971] datadog initial implementation to track logs

---

packages/cli/lib/sync.ts
packages/server/lib/controllers/environment.controller.ts
packages/server/lib/server.ts
packages/shared/lib/db/migrations/20230911164150_environment_variables_in_project_settings.cjs
packages/shared/lib/db/migrations/20230912181226_add_encryption_to_tables.cjs
packages/shared/lib/models/Environment.ts
packages/shared/lib/models/EnvironmentVariable.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/environment.service.ts
packages/shared/lib/utils/encryption.manager.ts
packages/webapp/src/pages/ProjectSettings.tsx
packages/webapp/src/utils/api.tsx

Resolves #763 
Provides groundwork for #932

[Github #763] env variables

---

docs-v2/guides/webhooks.mdx
packages/node-client/lib/index.ts
packages/shared/lib/index.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/data/data.service.integration.test.ts
packages/shared/lib/services/sync/data/data.service.ts
packages/shared/lib/services/sync/data/data.service.unit.test.ts
packages/shared/lib/services/sync/data/delete.service.integration.test.ts
packages/shared/lib/services/sync/data/delete.service.ts
packages/shared/lib/services/sync/data/mocks.ts
packages/shared/lib/services/sync/data/records.service.ts
packages/shared/lib/services/sync/orchestrator.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/webhook.service.ts
packages/webapp/src/types.ts

[Github #975] delete improvements

---

packages/node-client/lib/index.ts
packages/server/lib/controllers/sync.controller.ts
packages/server/lib/server.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/db/migrations/20230914080128_add_run_in_to_job.cjs
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/sync/job.service.ts
packages/worker/lib/activities.ts

[gh-#913] pause and restart sync from the sdk

---

packages/cli/lib/sync.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/db/migrations/20230914161744_add_auto_start_to_config.cjs
packages/shared/lib/integrations/index.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/nango-config.service.ts
packages/shared/lib/services/sync/config.service.ts
packages/shared/lib/services/sync/config.service.unit.test.ts
packages/shared/lib/services/sync/sync.service.ts

[gh-#992] auto_start implementation

---

packages/server/lib/controllers/connection.controller.ts

[gh-#1003] Fix force refresh from UI

---

packages/webapp/src/pages/ConnectionCreate.tsx
packages/webapp/src/pages/IntegrationCreate.tsx
packages/webapp/src/pages/ProjectSettings.tsx

[gh-#929] autocomplete off

---

package-lock.json
packages/shared/lib/services/webhook.service.ts
packages/shared/package.json

Resolves #687 with 10 retries to the provided webhook endpoint

[gh-#687] webhook retry

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/services/environment.service.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

[gh-#1027] allow deletion of env variables

---

packages/shared/lib/services/connection.service.ts

Potentially resolves #1016 and #988 
Refactored the `refreshOauth2CredentialsIfNeeded`. A potential issue is that on refresh failure the promise doesn't get removed from in memory so it will always fall back to the failed promise refresh. This could be the cause of issues users were seeing.

[gh-#1016] refactor

---

packages/shared/lib/services/sync/config.service.ts
packages/webapp/src/pages/Syncs.tsx

[gh-#1009] actual empty returns with model protection

---

integration-templates/hubspot/hubspot-owner.ts
integration-templates/hubspot/hubspot-service-tickets.ts
integration-templates/hubspot/hubspot-user.ts

Hubspot pagination is not working correctly, only the first page is always returned

Hubspot integration paging issue

---

packages/cli/lib/action.ejs
packages/cli/lib/sync.ts
packages/shared/lib/sdk/sync.ts

[gh-#993] NangoAction & NangoSync helpers

---

packages/shared/lib/services/sync/config/deploy.service.ts
packages/webapp/src/pages/Activity.tsx

[gh-#1061] better message and better json print logic

---

integration-templates/hubspot/hubspot-knowledge-base.ts
integration-templates/hubspot/nango.yaml

Resolves #1065 
Endpoint information gathered from https://community.hubspot.com/t5/Knowledge-Base-Tool/Knowledge-Base-API-Documentation/m-p/285319

[gh-#1065] add hubspot knowledge base integration script

---

package-lock.json
packages/frontend/lib/index.ts
packages/frontend/package.json
packages/server/lib/controllers/config.controller.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/unauth.controller.ts
packages/server/lib/server.ts
packages/shared/lib/models/Auth.ts
packages/shared/lib/services/connection.service.ts
packages/shared/providers.yaml
packages/webapp/package-lock.json
packages/webapp/package.json
packages/webapp/src/pages/ConnectionCreate.tsx
packages/webapp/src/pages/ConnectionDetails.tsx
packages/webapp/src/pages/Syncs.tsx
packages/webapp/src/types.ts
scripts/validation/providers/schema.json

[gh-#1014] unauthenticated conntion

---

integration-templates/salesforce/nango.yaml
integration-templates/salesforce/salesforce-tickets.ts

[gh-#1069] add salesforce-ticket integration script

---

docs-v2/spec.yaml
packages/node-client/lib/types.ts
packages/server/lib/controllers/proxy.controller.ts
packages/server/lib/models.ts
packages/shared/lib/models/Provider.ts
packages/shared/providers.yaml

[gh-#1075] decompress option

---

packages/server/lib/controllers/proxy.controller.ts

[gh-#1075] decompress for other endpoints

---

packages/cli/lib/utils.ts
packages/server/lib/controllers/proxy.controller.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/models/Generic.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/error.ts
packages/webapp/src/pages/Activity.tsx

Resolves #1091 
Resolves #1025

[Github #1091] action improvements

---

packages/shared/lib/services/sync/data/data.service.ts
packages/shared/lib/services/sync/data/delete.service.integration.test.ts
packages/shared/lib/services/sync/data/delete.service.ts
packages/shared/lib/services/sync/data/mocks.ts
packages/shared/lib/services/webhook.service.ts

Cleans up #1094 
Follow up to #1095

[gh-#1094] make call more specific for updatedKeys only

---

.github/workflows/audit.yaml
package-lock.json

[gh-#1104] update packages

---

packages/server/lib/utils/utils.ts
packages/server/lib/utils/utils.unit.test.ts

[gh-#1110] remove unused blocking call

---

docs-v2/spec.yaml
packages/server/lib/controllers/config.controller.integration.test.ts
packages/server/lib/controllers/config.controller.ts
packages/shared/lib/models/Provider.ts
packages/webapp/src/pages/IntegrationCreate.tsx

[gh-#1109] add syncs to the get integration object

---

packages/frontend/lib/index.ts
packages/server/lib/utils/utils.ts

Resolves #571 on top of https://github.com/NangoHQ/nango/pull/1073

[gh-#573] types and messaging cleanup

---

packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/data/data.service.ts
packages/shared/lib/services/sync/data/delete.service.integration.test.ts
packages/shared/lib/services/sync/data/delete.service.ts
packages/shared/lib/services/sync/data/records.service.ts
packages/shared/lib/services/sync/run.service.ts

[gh-#1119] improve accounting when track_deletes is set to true

---

package-lock.json
packages/shared/lib/services/sync/integration/integration.service.ts
packages/shared/lib/services/sync/integration/integration.service.unit.test.ts
packages/shared/package.json

Due to memory spikes, temporarily rollback to vm2

[gh-#790] vm2 temp

---

docs-v2/spec.yaml
packages/node-client/lib/index.ts
packages/node-client/lib/types.ts
packages/server/lib/controllers/config.controller.integration.test.ts
packages/server/lib/controllers/config.controller.ts
packages/shared/lib/models/Provider.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/sync/config/config.service.ts

[Github #1120] fix get integration with actions

---

packages/server/lib/controllers/activity.controller.ts
packages/server/lib/server.ts
packages/shared/lib/models/Activity.ts
packages/shared/lib/services/activity/activity.service.ts
packages/webapp/src/pages/Activity.tsx

Resolves #1121 
Brings load time from 13 seconds to about 1.5 seconds

[gh-#1121] load in messages as part of a separate endpoint

---

packages/shared/lib/db/migrations/20231018115215_add_pending_delete.cjs
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/sync/data/data.service.ts
packages/shared/lib/services/sync/data/delete.service.integration.test.ts
packages/shared/lib/services/sync/data/delete.service.ts
packages/shared/lib/services/sync/data/records.service.ts
packages/shared/lib/services/sync/run.service.ts

[gh-#1132] don't delete records until the sync completes successfully

---

packages/server/lib/controllers/environment.controller.ts
packages/server/lib/server.ts
packages/shared/lib/db/migrations/20231018132226_add_webhook_option.cjs
packages/shared/lib/models/Environment.ts
packages/shared/lib/services/environment.service.ts
packages/shared/lib/services/webhook.service.ts
packages/webapp/src/pages/ProjectSettings.tsx
packages/webapp/src/utils/api.tsx

Resolves #1134 
Adds an option under project settings:
Defaults to false which is the current behavior

[gh-#1134] add always send webhook option

---

packages/worker/lib/workflows.ts

[gh-#1136] bump to 24 hours

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/webapp/src/pages/Activity.tsx
packages/webapp/src/pages/ProjectSettings.tsx
packages/worker/package.json

[gh-#1138] fix error and scroll timing

---

packages/cli/lib/utils.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/index.ts
packages/shared/lib/services/connection.service.ts
packages/shared/lib/services/sync/config/deploy.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/metrics.manager.ts
packages/worker/lib/activities.ts

[Github #1152] script observability

---

packages/shared/lib/db/migrations/20231020102155_sync_job_table_indexes.cjs
packages/shared/lib/services/sync/sync.service.ts
packages/webapp/src/pages/ConnectionDetails.tsx
packages/webapp/src/pages/FlowCreate.tsx
packages/webapp/src/types.ts
packages/webapp/src/utils/utils.tsx

[Github #991] sync runtime in dashboard

---

packages/server/lib/controllers/proxy.controller.ts
packages/server/lib/controllers/proxy.controller.unit.test.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/sync/run.service.unit.test.ts
packages/worker/lib/integration.service.ts

Resolves #1156 
Also fixes community reported error of headers being transformed to lower case when using the proxy

[Github #1156] return action error

---

packages/frontend/lib/index.ts

[Github #1154] auth error

---

docs-v2/sdks/node.mdx
packages/node-client/lib/index.ts
packages/node-client/lib/types.ts
packages/shared/lib/services/sync/data/records.service.ts

Allow filtering with "added,update"

[gh-#1170] added,updated record filter

---

packages/server/lib/controllers/proxy.controller.ts

[gh-#1174] allow unauthenticated requests

---

packages/cli/lib/action.ejs
packages/cli/lib/local-integration.service.ts
packages/cli/lib/sync.ejs
packages/cli/lib/sync.ts
packages/cli/lib/utils.ts
packages/shared/lib/integrations/index.ts
packages/shared/lib/services/nango-config.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/error.ts
packages/shared/lib/utils/utils.ts
packages/webapp/src/pages/Activity.tsx
packages/worker/lib/integration.service.ts

Resolves #1178 -- see the issue for improvements

[Github #1178] action improvements

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/lib/sync.ts
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/lib/controllers/apiAuth.controller.ts
packages/server/lib/controllers/appAuth.controller.ts
packages/server/lib/controllers/auth.controller.ts
packages/server/lib/controllers/config.controller.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/oauth.controller.ts
packages/server/lib/controllers/sync.controller.ts
packages/server/lib/controllers/unauth.controller.ts
packages/server/package.json
packages/shared/lib/index.ts
packages/shared/lib/services/connection.service.ts
packages/shared/lib/utils/analytics.ts
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

[Github #1161] telemetry update

---

packages/server/lib/controllers/proxy.controller.ts
packages/server/lib/controllers/proxy.controller.unit.test.ts
packages/shared/providers.yaml

[gh-#1168] inject shopify accessToken into the header

---

packages/webapp/src/components/LeftNavBar.tsx

This PR improves the sidebar ui to have more consistent styling.
P.S.
This is my first PR for this repo and I was not able to find any sort of contribution guide. If their is anything else that is needed please let me know.

refactor(webapp): improve sidebar ui design

---

packages/node-client/lib/index.ts
packages/shared/lib/sdk/sync.ts

[gh-#1189] triggerAction from a sync / action

---

packages/cli/lib/index.ts
packages/cli/lib/sync.ts
packages/cli/lib/types.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/services/sync/sync.service.ts

[gh-#1198] fix version mismatch

---

packages/server/lib/controllers/provider.controller.ts
packages/server/lib/server.ts

[GitHub  #1182] add providers controller

---

packages/server/lib/controllers/proxy.controller.ts
packages/server/lib/controllers/proxy.controller.unit.test.ts
packages/shared/lib/services/activity/activity.service.ts

[gh-#1201] don't expose authorization in the header

---

packages/cli/lib/sync.ts
packages/server/lib/controllers/connection.controller.ts
packages/shared/lib/utils/error.ts

[gh-#1205] import app connection

---

packages/webapp/src/pages/ProjectSettings.tsx

- fixes: #1194
It shows web-app behavior after changes.
https://github.com/NangoHQ/nango/assets/77796540/144b0012-d3cc-401f-8ca9-4598e850af76

feat: key rotation warning

---

packages/shared/lib/services/sync/orchestrator.service.ts

[gh-#1209] update activity log messages for pause/start sync

---

package.json
packages/server/.gitignore
packages/server/nango-integrations/flow-result-notifier-action.ts
packages/server/nango-integrations/nango.yaml
packages/server/package.json
packages/shared/lib/clients/sync.client.ts

[gh-#1213] if not writing logs don't use the oldActivityLogId & add nango-integrations directory

---

integration-templates/confluence/confluence-pages.ts
integration-templates/confluence/confluence-spaces.ts
packages/shared/providers.yaml

[Github #1215] pagination follow ups

---

packages/node-client/lib/types.ts
packages/shared/lib/models/Connection.ts
packages/shared/lib/services/connection.service.ts

[gh-#1220] fix type mismatches

---

docs-v2/api-reference/integration/create.mdx
docs-v2/api-reference/integration/update.mdx
docs-v2/spec.yaml
packages/node-client/lib/index.ts
packages/server/lib/controllers/config.controller.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/sdk/sync.unit.test.ts
packages/webapp/src/pages/GettingStarted.tsx

* Resolves #1226 
* Resolves #1224

[Github #1226] fix provider lookup

---

packages/shared/lib/db/migrations/20231106085744_add_sync_index.cjs
packages/shared/lib/services/sync/sync.service.ts

[gh-#1228] update deleted_at flag

---

package-lock.json
packages/cli/docker/docker-compose.yaml
packages/cli/package.json
packages/frontend/package.json
packages/node-client/package.json
packages/server/package.json
packages/shared/lib/db/migrations/20231106121117_delete_connection_improvements.cjs
packages/shared/package.json
packages/webapp/package-lock.json
packages/webapp/package.json
packages/worker/package.json

[gh-#1231] add additional indexes

---

packages/shared/lib/utils/analytics.ts
packages/webapp/src/pages/Signup.tsx

[gh-#1235] add web account signup event

---

packages/cli/lib/sync.ts
packages/cli/lib/utils.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/run.service.ts

[gh-#1046] don't compile fully if the model name is incorrect

---

packages/shared/lib/db/database.ts
packages/shared/lib/db/seeders/activity.seeder.ts
packages/shared/lib/db/seeders/config.seeder.ts
packages/shared/lib/db/seeders/connection.seeder.ts
packages/shared/lib/services/environment.service.ts
packages/shared/lib/services/sync/data/data.service.integration.test.ts
tests/setup.ts
vite.integration.config.ts

[Github #1238] integration tests

---

packages/server/lib/controllers/proxy.controller.ts
packages/server/lib/controllers/proxy.controller.unit.test.ts

[gh-#1201] strip away unauth token when included

---

packages/webapp/src/pages/ProjectSettings.tsx

[gh-#1253] allow hmac edits

---

packages/frontend/lib/index.ts

[gh-#1252] params not required

---

packages/server/lib/controllers/onboarding.controller.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/services/sync/orchestrator.service.ts
packages/shared/lib/services/sync/sync.service.ts
packages/shared/lib/utils/error.ts

[gh-#1256] do lookup if connection is provided as well

---

docs-v2/sdks/node.mdx
docs-v2/spec.yaml
packages/node-client/lib/types.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/services/sync/orchestrator.service.ts
packages/webapp/src/utils/utils.tsx

[gh-#1258] sync status add properties

---

packages/node-client/lib/types.ts
packages/shared/lib/sdk/sync.ts

[gh-#1267] extend credentials common

---

integration-templates/google-calendar/google-calendar-events.ts
integration-templates/google-calendar/google-calendars.ts
integration-templates/google-calendar/nango.yaml
packages/shared/flows.yaml
packages/shared/providers.yaml

Adds pagination and proxy for google and adds a google-calendars and google-calendar-events sync

[gh-#1216] add google pagination and gcal syncs

---

integration-templates/google-calendar/nango.yaml
packages/cli/lib/local-integration.service.ts
packages/node-client/lib/index.ts
packages/node-client/lib/types.ts
packages/shared/lib/sdk/sync.ts

[gh-#1270] allow responseType

---

packages/frontend/lib/index.ts

Resolves #1272 
Can be set with providing a width and height to the FE SDK
```
new Nango({ host: hostUrl, websocketsPath, publicKey, width: 600, height: 800 });
```

[gh-#1272] allow modal width / height to be optionally set and fix AuthError response

---

packages/cli/lib/services/dryrun.service.ts

[gh-#1279] parse stubbed metadata

---

packages/shared/lib/services/onboarding.service.ts

[gh-#1281] correct step

---

packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/activity/activity.service.ts
packages/shared/lib/services/sync/notification/webhook.service.ts

[gh-#1283] more quiet logging

---

packages/webapp/src/pages/IntegrationCreate.tsx

[gh-#929] add hidden field

---

packages/node-client/lib/types.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/paginate.service.ts
packages/shared/providers.yaml

Resolves #1288 
- Also fixes pipedrive base_url
- Adds pipedrive pagination

[gh-#1288] fix put and fix pipedrive api

---

package-lock.json
packages/server/lib/server.ts
packages/server/package.json

[gh-#1291] add apm via datadog if cloud

---

packages/frontend/lib/index.ts

Reverts #1299 due to reported regression cc/ @TBonnin

[gh-#1251] rollback processingMessage

---

packages/frontend/lib/index.ts
packages/server/lib/controllers/apiAuth.controller.ts
packages/webapp/src/pages/ConnectionCreate.tsx

[gh-#1308] allow empty basic auth username

---

packages/cli/lib/templates/nango.yaml

[gh-#1319] init with v1 yaml for now

---

packages/shared/lib/services/sync/data/records.service.ts

[gh-#1325] 1 minute timeout on getRecords call

---

packages/shared/lib/services/sync/data/records.service.ts
packages/shared/lib/utils/metrics.manager.ts

Adds metrics for deprecated features before we deprecate
Resolves #1323

[gh-#1323] add deprecation observability

---

packages/frontend/lib/index.ts

Add back auth window closing detection

bringing back auth window closing detection

---

packages/webapp/src/pages/ProjectSettings.tsx

Fixes a bug with how environment variables are loaded when the project environment is switched
Resolves #1339

[gh-#1339] fix env variables bug

---

packages/webapp/src/pages/ProjectSettings.tsx

Fixes additional issue found while testing on staging when an unsaved env variable exists
#1351

[gh-#1351] fix additional small bug when switching envs and an unsaved var exists

---

docs-v2/integrations/all/close.mdx
docs-v2/integrations/crm.mdx
docs-v2/mint.json
packages/shared/providers.yaml

Adds Close API provider
Resolves #1355

[gh-#1355] add close api provider

---

packages/shared/lib/services/connection.service.ts
packages/shared/lib/utils/metrics.manager.ts

Adds observability events for token refreshes
NAN-58

[nan-58] token refresh observability

---

packages/shared/lib/services/sync/data/records.service.ts
packages/shared/lib/utils/metrics.manager.ts

Query improvements for list records

[nan-103] talkbase fix list records error

---

packages/cli/lib/services/local-integration.service.ts
packages/shared/lib/services/sync/job.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/error.ts
packages/worker/lib/activities.ts
packages/worker/lib/integration.service.ts

Sets sync type properly if auto_start is true

[nan-112] set sync type properly if auto_start is true

---

packages/shared/lib/services/proxy.service.unit.test.ts

I was investigating Talkbase issue with retrying where requests to discord were waiting for 5000+ seconds and added tests to confirm that the retry logic in proxy.service is correct

Adds tests for proxy retry logic

---

docs-v2/api-reference/connection/list.mdx
docs-v2/sdks/node.mdx
docs-v2/spec.yaml
packages/node-client/lib/types.ts
packages/server/lib/controllers/connection.controller.ts
packages/shared/lib/services/connection.service.ts

Adds metadata to the `listConnections` call
NAN-100

[nan-100] add metadata

---

packages/shared/flows.yaml
packages/shared/providers.yaml
packages/webapp/src/pages/FlowCreate.tsx
scripts/flows.js

Allow google-drive sync and actions to be exposed in the UI
NAN-127

[nan-127] update google drive api

---

packages/webapp/public/images/template-logos/google-drive.svg
packages/webapp/src/pages/FlowCreate.tsx

Update to NAN-127 to handle non arrays for a model
NAN-127

[nan-127] fix array issue and add google-drive icon

---

packages/shared/lib/db/migrations/20231213124728_drop_sync_data_records_indexes.cjs

Comments out migrations that cause errors when not existing on non cloud environments

comment out migration that is causing issues

---

packages/server/lib/controllers/flow.controller.ts
packages/shared/lib/services/sync/config/config.service.ts
packages/shared/lib/services/sync/sync.service.ts
packages/webapp/src/pages/Syncs.tsx

Fixes bad query with conflicting sync names when deleting a prebuilt flow
NAN-182

[nan-182] pass more information in flow delete call to perform the correct query

---

packages/shared/lib/services/sync/sync.service.ts

Additional fix and check for missing syncs and create them if needed
NAN-182

[nan-182] create missing syncs even if some are active

---

packages/runner/lib/client.unit.test.ts
packages/runner/lib/exec.ts

Make setTimeout available in node.vm context

---

packages/jobs/lib/temporal.ts
packages/shared/lib/services/file/remote.service.ts

Few more enterprise specific updates
NAN-164

[nan-164] update enterprise logic

---

packages/jobs/lib/runner/runner.ts

Hotfix for render runner issue

default back to local runner if render runner isn't ever accessible

---

packages/jobs/lib/runner/runner.ts
packages/shared/lib/models/Activity.ts
packages/shared/lib/utils/metrics.manager.ts

On a render failure due to a recent incident from render fallback to a local instance. This adds in observability to know if that happens

add in metrics manager

---

packages/shared/lib/services/connection.service.ts

Activity log becomes filled with this log which makes it hard to find anything

remove noisy activity log entry

---

packages/shared/lib/services/connection.service.ts

Allows a private key to be used if it has line breaks or not.

[nan-170] test for line breaks or not

---

packages/webapp/src/pages/Activity.tsx
packages/webapp/src/pages/ConnectionDetails.tsx

For some customers pages are still a bit slow. Show an indicator that the page is loading
Partial of https://linear.app/nango/issue/NAN-51/[summit]-improve-activity-tab

spinner on slow pages

---

packages/cli/lib/services/local-integration.service.ts
packages/jobs/lib/integration.service.ts
packages/runner/lib/exec.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/utils/error.manager.ts
packages/shared/lib/utils/error.ts

Add `ActionError` object to allow an action a specific error.
NAN-171

[nan-171] allow ActionError response

---

packages/server/lib/controllers/webhook.controller.ts
packages/server/lib/server.ts
packages/shared/lib/integrations/scripts/webhook/index.ts
packages/shared/lib/integrations/scripts/webhook/slack-webhook-routing.ts
packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
packages/shared/lib/services/nango-config.service.ts
packages/shared/lib/services/sync/notification/webhook.service.ts
packages/shared/providers.yaml

Adds slack support for webhooks
NAN-176

[NAN-176] Add slack webhook support

---

.github/workflows/deploy-runners.yaml
scripts/deploy/runners.bash
scripts/deploy/test.runners.bash

Adds a github action to allow runners to be deployed to programmatically
NAN_207

[nan-207] add github action and bash script

---

packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
packages/shared/lib/utils/metrics.manager.ts

Adds webhook issue events to better track why a webhook might not come through in the nango sync

add webhook issue types for better debugging

---

packages/cli/lib/services/model.service.ts
packages/cli/lib/sync.unit.test.ts

Allows models with a `s`
Resolves #1441 / NAN-180

[nan-180] don't strip s

---

docs-v2/sdks/node.mdx

Updates docs for updateMetadata
NAN-72

[nan-72] update node metadata docs

---

packages/cli/lib/utils.ts

Makes the secret key missing warning a bit clearer
NAN-174

[nan-174] update secret key warning

---

packages/cli/lib/index.ts

Improves docs of the dryrun command
NAN-173

[nan-173] improve docs

---

packages/server/lib/controllers/webhook.controller.ts
packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
packages/shared/lib/utils/metrics.manager.ts

Cleans up incoming webhook parsing

Webhook debugging

---

packages/server/lib/controllers/webhook.controller.ts
packages/server/lib/utils/utils.ts

Add global flag for webhooks
NAN-220

[NAN-220] webhook production measures

---

.github/workflows/integration-flows.yaml
.github/workflows/push-container.yaml
package-lock.json
packages/cli/package.json
packages/jobs/package.json
packages/runner/package.json
packages/server/package.json
packages/shared/package.json
scripts/publish.sh

Fix: update the version of shared and node-client in the different package.json files once the new version is published. 
Fix: run flow.js when building container images

fix npm publish: update shared and node package version in package.json

---

packages/webapp/src/pages/Activity.tsx

Hide filters if no activities present

[nan-177] don't show filters if no activity logs period

---

packages/shared/lib/services/sync/config/config.service.ts

[nan-177] only grab actives

---

packages/cli/lib/services/local-integration.service.ts

setTimeout should be available in script when running in dry-run mode.
https://linear.app/nango/issue/NAN-225/[talkbase]-enable-settimeout-locally

Allow usage of setTimeout in script when running dry-run

---

packages/cli/lib/cli.ts
packages/server/lib/controllers/environment.controller.ts
packages/server/lib/server.ts
packages/server/lib/utils/utils.ts
packages/shared/lib/utils/utils.ts

Version is misreported, this fixes it

fix version lookup

---

packages/webapp/src/pages/Activity.tsx

Fixes bad behavior of a user getting stuck if they select a script filter
NAN-228

[nan-228] add script

---

packages/cli/lib/cli.ts
packages/shared/lib/integrations/scripts/webhook/slack-webhook-routing.ts

Adds more robust slack webhook handling to deal with oddities and also nan-180 addition to handle `s` in model names
NAN-219 & NAN-180

[nan-219] tighten up slack webhook handling

---

packages/server/lib/controllers/config.controller.ts
packages/shared/lib/utils/error.ts

Verifies the key has the correct header
NAN-170

[nan-170] verify key is valid

---

.github/workflows/publish.yaml

Show version number in the commit message automatically generated by publishing packages

show version in auto commit message

---

scripts/deploy/runners.bash

Cleans up runner deploy logic
NAN-227

[NAN-227] Render runner deployment logic pagination fix

---

packages/shared/lib/integrations/scripts/webhook/hubspot-webhook-routing.ts
packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
packages/shared/lib/services/connection.service.ts

- Allow multiple connections to be apart of a single webhook
- Order hubspot webhooks by time
NAN-226

[nan-226] webhook improvements

---

packages/frontend/lib/index.ts
packages/server/lib/clients/publisher.client.ts
packages/server/lib/clients/publisher.client.unit.test.ts
packages/server/lib/controllers/appAuth.controller.ts
packages/server/lib/controllers/config.controller.integration.test.ts
packages/server/lib/controllers/config.controller.ts
packages/server/lib/controllers/oauth.controller.ts
packages/server/lib/utils/web-socket-error.ts
packages/shared/lib/integrations/scripts/webhook/github-app-webhook-routing.ts
packages/shared/lib/integrations/scripts/webhook/hubspot-webhook-routing.ts
packages/shared/lib/integrations/scripts/webhook/index.ts
packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
packages/shared/lib/services/activity/activity.service.ts
packages/shared/lib/services/connection.service.ts
packages/shared/providers.yaml
packages/webapp/src/pages/ConnectionCreate.tsx
packages/webapp/src/pages/IntegrationCreate.tsx

Adds in logic to handle a github app requester flow
NAN-234

[NAN-234] Github app requester flow implementation

---

integration-templates/greenhouse-basic/greenhouse-applications.ts
integration-templates/greenhouse-basic/greenhouse-candidates.ts
integration-templates/greenhouse-basic/greenhouse-jobs.ts

Fix pagination on greenhouse.
This provider has been used successfully in local development to connect to Greenhouse and successfully call those endpoints after authorizing using Nango.

Fix pagination on greenhouse

---

docs-v2/integration-templates/overview.mdx
docs-v2/integration-templates/workable.mdx
docs-v2/mint.json
integration-templates/workable/nango.yaml
integration-templates/workable/workable-candidates-activities.ts
integration-templates/workable/workable-candidates-offer.ts
integration-templates/workable/workable-candidates.ts
integration-templates/workable/workable-create-candidate.ts
integration-templates/workable/workable-create-comment.ts
integration-templates/workable/workable-jobs-candidates.ts
integration-templates/workable/workable-jobs-questions.ts
integration-templates/workable/workable-jobs.ts
integration-templates/workable/workable-members.ts
packages/shared/flows.yaml
packages/webapp/public/images/template-logos/workable.svg

Added sync and action integration templates for Workable, covering candidates, candidate activities, jobs, candidates for specified jobs, questions for specified jobs, and members. The templates include actions to create candidate for the job and comment on the candidate.
##Test
I have successfully implemented synchronization for Workable, utilizing this provider to establish connections in local development. The integration has proven effective in syncing Workable candidates, candidate activities, jobs, candidates for specified jobs, questions for specified jobs, and members. It includes actions to create candidate for the job and comment on the candidate.

Added integration templates for workable

---

packages/cli/lib/services/verification.service.ts
packages/shared/lib/services/file/remote.service.ts
packages/shared/lib/services/proxy.service.ts

Throws an error to fix action behavior in the event of an API error
NAN-246

[NAN-246] proxy error should throw instead of returning

---

.github/workflows/deploy.yaml
packages/server/lib/controllers/config.controller.ts
packages/shared/lib/integrations/scripts/webhook/hubspot-webhook-routing.ts
packages/shared/lib/integrations/scripts/webhook/hubspot-webhook-routing.unit.test.ts
packages/webapp/src/components/ui/input/SecretTextArea.tsx

Order a payload by creation
NAN-226 & NAN-170

Nan 226 payload ordering

---

packages/server/lib/controllers/config.controller.ts

allow custom to be added on edit for web

---

packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
packages/shared/lib/services/sync/notification/webhook.service.ts

Forward all webhook headers
Customer feedback on NAN-234

Nan 234 forward headers

---

packages/server/lib/controllers/connection.controller.ts

Hackerrank requires a password to be empty

allow empty password

---

packages/shared/providers.yaml

Added pagination configuration for greenhouse in providers.yaml.

Added pagination configuration for greenhouse

---

packages/server/lib/controllers/oauth.controller.ts
packages/shared/lib/integrations/scripts/connection/github-app-oauth-post-connection.ts

Include the handle when connecting using a github oauth app and it is not a request flow
NAN-234

[nan-234] only update creds if the cred type is oauth

---

packages/shared/lib/services/sync/notification/slack.service.ts

If the action fails don't cascade down to the sync
NAN-264
- jobs

[nan-264] better reporting and protective call if the action fails

---

docs-v2/integrations/all/google-ads.mdx
package-lock.json
packages/cli/package.json
packages/shared/providers.yaml
packages/webapp/public/images/template-logos/google-ads.svg

Add google-ads provider

---

packages/cli/lib/services/model.service.ts

Allow for dynamic field modeling in the nango.yaml
```
Contact:
id: string
userId: string
__string: string
```
NAN-267

allow dynamic properties in yaml

---

package-lock.json
packages/shared/package.json

CLI has a bug with the current version

hotfix: explicitly install qs

---

packages/server/lib/controllers/access.middleware.ts

Attach account id and environment Id to trace in server access middleware
https://linear.app/nango/issue/NAN-257/add-account-id-andor-environment-id-to-apm-traces
Tested in staging

server: link account and environment to authenticated trace

---

packages/webapp/src/pages/Activity.tsx

Fixes missing https in url and updates copy logic so it is more specific and surface-able
NAN-237

[nan-237] add https and tweak copyButton logic to be more specific

---

packages/server/nango-integrations/flow-result-notifier-action.ts
packages/shared/lib/services/proxy.service.ts
packages/shared/lib/services/sync/notification/slack.service.ts
packages/shared/providers.yaml

More specific messaging around retries based off a customer complaint
NAN-272

[nan-272] better messaging, adds retry for zendesk and more specific slack notification link

---

docs-v2/api-reference/sync/update-connection-frequency.mdx
docs-v2/mint.json
docs-v2/sdks/node.mdx
docs-v2/spec.yaml
packages/node-client/lib/index.ts
packages/node-client/lib/types.ts

Follow up of #1548
- Update node-client
- Update open api
- Update documentation

fix: update sync connection frequency tooling and documentation

---

packages/webapp/package-lock.json
packages/webapp/package.json
scripts/publish.sh

I forgot to bump @nangohq/frontend version in webapp package after publishing

fix: update frontend version in webapp package after publication

---

integration-templates/linear/linear-projects.ts
integration-templates/linear/nango.yaml

Add `url` property to `LinearProject` model
N / A

Include Linear project URL in model

---

packages/webapp/src/pages/Activity.tsx

I changed the SVG attributes to use camelCase. Additionally, I switched up the order between integration and connection filters.

fix warnings on Activity

---

docs-v2/integrations/all/github.mdx
packages/cli/lib/cli.ts
packages/cli/lib/fixtures/nango-yaml/v2/valid/object.json
packages/cli/lib/nango.yaml.schema.v2.json
packages/cli/lib/templates/post-connection.ejs
packages/shared/lib/integrations/scripts/connection/connection.manager.ts
packages/shared/lib/integrations/scripts/connection/index.ts
packages/shared/lib/integrations/scripts/connection/salesforce-post-connection.ts
packages/shared/lib/integrations/scripts/webhook/index.ts
packages/shared/lib/integrations/scripts/webhook/internal-nango.ts
packages/shared/lib/integrations/scripts/webhook/salesforce-webhook-routing.ts
packages/shared/lib/models/NangoConfig.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/nango-config.service.ts
packages/shared/providers.yaml

Update docs for github-app-oauth and adds gotchas

Docs Update for Github App OAuth & Salesforce webhook handling

---

packages/server/lib/controllers/apiAuth.controller.ts
packages/server/lib/controllers/appAuth.controller.ts
packages/server/lib/controllers/appStoreAuth.controller.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/environment.controller.ts
packages/server/lib/controllers/oauth.controller.ts
packages/server/lib/controllers/unauth.controller.ts
packages/server/lib/server.ts
packages/shared/lib/db/migrations/20240131121245_add_auth_webhook_option.cjs
packages/shared/lib/hooks/hooks.ts
packages/shared/lib/index.ts
packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
packages/shared/lib/models/Auth.ts
packages/shared/lib/models/Connection.ts
packages/shared/lib/models/Environment.ts
packages/shared/lib/models/Sync.ts
packages/shared/lib/models/Webhook.ts
packages/shared/lib/services/connection.service.ts
packages/shared/lib/services/environment.service.ts
packages/shared/lib/services/notification/slack.service.ts
packages/shared/lib/services/notification/webhook.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/webapp/src/pages/ProjectSettings.tsx
packages/webapp/src/utils/api.tsx

Send an webhook on connection creation or failure
NAN-281

[NAN-281] auth failure/creation webhooks

---

packages/shared/providers.yaml

Fix Square scope separator

---

docs-v2/integrations/all/gusto.mdx
packages/shared/providers.yaml

Add Gusto Demo API

---

packages/persist/lib/controllers/persist.controller.ts
packages/persist/lib/server.ts
packages/persist/lib/server.unit.test.ts
packages/shared/lib/sdk/sync.ts

commit 1: Persist doesn't log the errors. Making sure we log the response if it is an error
commit 2: pass lastSyncDate = now if undefined

persist: improve errors logging + lastSyncDate = new Date if undefined

---

packages/persist/lib/controllers/persist.controller.ts
packages/persist/lib/utils/result.ts
packages/shared/lib/sdk/sync.ts

Adding logging when call to persist API fails
Fix tracing error in persist API

Persist API: more logging and fix tracing error

---

packages/shared/lib/services/file/remote.service.ts
packages/shared/lib/utils/utils.ts
packages/webapp/src/pages/GettingStarted.tsx

Authorize step wasn't tracked correctly
NAN-278

[nan-278] fix authorize tracking step

---

packages/cli/lib/templates/nango.yaml

Type in the sync template is misleading

remove extra s

---

packages/shared/lib/services/notification/webhook.service.ts

Check for the webhook URL as well

check for webhook url

---

packages/server/lib/utils/utils.ts
packages/shared/providers.yaml

Add support for clari-copilot and add parsing of the template.proxy.headers

[nan-287] add support for clari-copiloti

---

packages/shared/lib/sdk/sync.ts
packages/shared/lib/utils/utils.ts
packages/webapp/src/pages/Activity.tsx

Update nango.log to accept a recursive object
NAN-306

[nan-306] log update

---

packages/shared/lib/services/notification/webhook.service.ts
packages/shared/lib/services/notification/webhook.service.unit.test.ts

Improves variable name for the webhook service and adds unit tests
NAN-317

[nan-317] better variable names and add webhook test

---

packages/shared/lib/services/proxy.service.ts
packages/shared/lib/services/proxy.service.unit.test.ts

Adds in proper parsing of an extra api key value when it is stored in the connection config
NAN-287

[nan-287] add in usage and test coverage

---

packages/webapp/src/pages/ConnectionDetails.tsx

Show metadata for all auth types
NAN-331

[nan-331] show metadata for all connection types

---

packages/cli/lib/fixtures/return-sync.ts
packages/cli/lib/fixtures/sync.ts
packages/cli/lib/fixtures/void-return-sync.ts
packages/cli/lib/services/parser.service.ts
packages/cli/lib/sync.unit.test.ts
packages/shared/lib/services/sync/run.service.ts

Removes return statement support and adds compile warning
NAN-65

[nan-65] remove return logic and add parser check

---

packages/webapp/src/pages/IntegrationCreate.tsx

Allow editing on the integration edit screen
NAN-337

[nan-337] fix check for value

---

packages/shared/lib/clients/sync.client.ts

Fixes action error checking for an error when an error could be null
NAN-338

[nan-338] optional chaining

---

packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/paginate.service.ts
packages/shared/lib/utils/utils.ts
packages/shared/lib/utils/utils.unit.test.ts

When paginating the base url gets included twice
NAN-339

[nan-339] protect against double inclusion of the base url

---

packages/server/lib/controllers/webhook.controller.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/metrics.manager.ts

Remove custom tags from the capture metrics call
NAN-327

[nan-327] remove tags from metrics

---

packages/cli/lib/fixtures/nested-return-sync.ts
packages/cli/lib/services/parser.service.ts
packages/cli/lib/sync.unit.test.ts

[nan-345] remove check for now

---

packages/server/lib/controllers/onboarding.controller.ts

- Run the demo every 5minutes to make it more interesting and lively
Contributes to NAN-279

fix(demo): run every 5minutes

---

packages/shared/lib/utils/utils.ts

Client wasn't being instantiated on local due to undefined check

fix test for undefined in isTest check

---

packages/shared/providers.yaml

https://developers.greenhouse.io/harvest.html#rate-limiting
https://linear.app/nango/issue/NAN-346/[kula]-retry-definition-for-greenhouse-provider

providers: add retry for greenhouse

---

.github/workflows/build-images.yaml
.github/workflows/push-container.yaml

I tested the `master` condition by removing it (https://github.com/NangoHQ/nango/pull/1664/commits/d6975d696313e5b80c0e2e48c43716d843034e7e) but it didn't tested the string formatting inside the condition. Turns out it wasn't okay.
You can check the formatting with the condition inverted https://github.com/NangoHQ/nango/pull/1667/commits/31b849f279159c983de434adb77959bab9e3c872
https://github.com/NangoHQ/nango/actions/runs/7892050973/job/21537690567

fix(ci): bad substition

---

packages/webapp/src/pages/ConnectionDetails.tsx

Restore the connection details as it has a feature that is unreleased yet and is causing bus
NAN-377

[nan-377] restore connection details

---

packages/runner/lib/exec.ts

Runners on prod seem to be stuck. Remove cancel logic to be able to restart/deploy runners
NAN-378

[nan-378] restore exec runner logic

---

packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/utils/metrics.manager.ts

We were tracking actions using apm and spans which samples but we want the full picture of actions. This is added by logs and using the volume and also tracking duration by using metrics with no tags.
NAN-192

[nan-192] action tracking

---

packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/sync/sync.service.ts

Contributes to NAN-305 and follow up of #1679 
When running a sync we would set it to null to let the user modify it, since it's not longer possible the backup strategy is now useless and we should always override.

fix(sync): always trust lastSyncDate

---

packages/server/lib/controllers/activity.controller.ts

The filters on the activity tab are inverted, I think it's just from the last PR #1648

fix(activity): UI filters are inverted

---

packages/shared/lib/services/file/remote.service.ts

Allow enterprise customers to use an s3 bucket
NAN-354

[nan-354] allow enterprise to pass in an aws bucket

---

packages/shared/providers.yaml

Updating Netsuite provider (proxy, scopes, auth params).

update netsuite provider

---

packages/shared/lib/clients/provider.client.ts

Finalize tiktok accounts integration
NAN-353

[nan-353] remove debug and additional checks

---

packages/webapp/src/pages/GettingStarted.tsx
packages/webapp/src/pages/Signup.tsx

Fixes NAN-352
Track events in Getting Started page. I tried to be exhaustive so we know if they dropped because of an error or just because they dropped.
This is something that will need to be ported in UI revamp @khaliqgant

fix(ui): track getting started

---

packages/jobs/lib/runner/render.runner.ts

- Add a way to enable sdk telemetry on dynamic runners

chore: enable sdk telemetry

---

packages/jobs/lib/crons/deleteOldActivities.ts

- Misspell Activities
- Add cpu nice to the list

fix(cron): env naming

---

packages/shared/lib/db/migrations/20240125102526_remove_decoupled_provider_config_key.cjs

[hotfix] check for objects

---

package-lock.json
packages/persist/lib/controllers/persist.controller.ts
packages/persist/package.json
packages/shared/lib/utils/telemetry.ts

We want to track total number of records persisted and total size so we can track change in usage pattern

persist: add total records count and size metrics

---

packages/cli/lib/fixtures/nango-yaml/v1/valid/object.json
packages/cli/lib/fixtures/nango-yaml/v2/valid/object.json
packages/shared/lib/db/migrations/20240125102526_remove_decoupled_provider_config_key.cjs
packages/shared/lib/models/NangoConfig.ts
packages/shared/lib/services/nango-config.service.ts
packages/shared/lib/services/sync/config/config.service.ts

[nan-428] fix legacy scripts and bad migration query

---

packages/shared/lib/services/sync/config/config.service.ts
packages/webapp/src/pages/Activity.tsx
packages/webapp/src/pages/Integration/FlowPage.tsx

Fixes downloading of private templates

Revamp followups

---

packages/shared/lib/services/sync/config/config.service.ts

Fix error `_nango_sync_endpoints` relation does not exist in the database

fix(nango_sync_endpoints):relation doesn't exist

---

packages/cli/scripts/v1-v2.js
packages/server/lib/controllers/config.controller.ts
packages/shared/lib/utils/utils.ts
packages/webapp/src/pages/Connection/Models.tsx

- Fix hosted temporal error when looking up flows
- Fix missing status for `ERROR`
- FIx flattening of output when there is a multi model return
NAN-426

Nan 426 other followups

---

packages/cli/scripts/v1-v2.js

Fix cli multi model output to endpoints

[NAN-426] fix cli update

---

packages/shared/lib/db/database.ts
packages/shared/lib/services/environment.service.ts

Start of a long effort on removing the schema everywhere and also fixing errors that could happen (reported on [slack](https://nango-community.slack.com/archives/C04ABR352H0/p1708685209570519?thread_ts=1708685072.874629&cid=C04ABR352H0))
- Add Search path force Postgres to look for table in this schema instead of public
- Test with one function

fix(db): add search path

---

packages/shared/lib/clients/sync.client.ts

Fixes NAN-442
Yesterday we had a crash after the error `Workflow execution already started` but we were calling so it made me think something was off. Turns out we need to await the result() and cancel() is just returning the response of the call not the actual cancellation.
- Fully await cancellation

fix(sync): await full cancel

---

docs-v2/reference/sdks/node.mdx
package-lock.json
packages/cli/lib/templates/nango.yaml
packages/cli/package.json

[nan-437] add in econn errors

---

packages/webapp/src/pages/Connection/Show.tsx
packages/webapp/src/pages/Connection/Syncs.tsx

Use `Syncs` instead of `Models` for the tab name.
NAN-408

[NAN-408] Syncs instead of Models

---

.yamllint
docs-v2/mint.json
docs-v2/reference/api/scripts/config.mdx
docs-v2/reference/sdks/node.mdx
docs-v2/spec.yaml
packages/node-client/lib/index.ts
packages/node-client/lib/types.ts
packages/server/lib/server.ts
packages/shared/lib/models/NangoConfig.ts

Alias flow/configs to `scripts/config` to better naming and update docs
NAN-457

[NAN-457] document script model introspection endpoint

---

packages/shared/lib/services/sync/data/records.service.ts

Reverts https://github.com/NangoHQ/nango/pull/1771 as it was not finished

temp revert

---

docs-v2/spec.yaml
packages/webapp/src/pages/Integration/APIReference.tsx
packages/webapp/src/pages/Integration/Scripts.tsx

Fix indentation in the yaml
NAN-457

[nan-457] fix documentation indentation and spelling issues

---

packages/webapp/src/components/LeftNavBar.tsx

Enterprise should be able to access user and team settings
NAN-495

show settings if cloud or enterprise

---

packages/shared/lib/db/migrations/20240304091237_clean-up-indexes.cjs

Fixes NAN-420
These indexes have not yielded any rows in +7days. Those are mostly single column indexes as expected.

fix(db): clean up indexes

---

packages/webapp/src/pages/Activity.tsx

Adds an additional trigger to ensure we have log messages to match to the parent log. With a log ravamp this should be changed so this is hopefully temporary-ish logic.
NAN-501

[nan-501] add updateLogs trigger

---

packages/server/lib/server.ts

Follow up #1766
I got a bit eager in my removal of import in everything but `app.ts`, except server does not have app.ts
- Reup nango api tracking

fix(dd): wrong import in server

---

packages/webapp/public/manifest.json

Fix properties `name` and `short_name` on app manifest.

fix(manifest):fix property names

---

packages/webapp/src/utils/utils.tsx

If an action has not output it would throw an error in the webapp
NAN-439

[nan-439] allow no output for script

---

packages/server/lib/controllers/sync.controller.ts

Fix usage or deprecated method when using the curl or sdk

don't use deprecated

---

packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/utils.ts

Enterprise customers can use s3 or store integration files locally.

[enterprise] check for usage of s3 for remote files

---

packages/node-client/lib/index.ts
packages/node-client/lib/types.ts
packages/server/lib/controllers/sync.controller.ts
packages/shared/lib/models/Webhook.ts
packages/shared/lib/services/notification/webhook.service.ts
packages/shared/lib/services/sync/data/records.service.ts

Decided that `modifiedAfter` is clearer than `updatedAfter`

use updatedAfter instead of modified after

---

packages/webapp/src/pages/Integration/AuthSettings.tsx

Display Integration ID whenever the user clicks on Edit. `onChange` input, display IntegrationMenu.

feat(webapp):improve input integration ID on edit

---

integration-templates/teamtailor/teamtailor-candidates.ts
packages/shared/providers.yaml

Reduce the page size for the example sync template.

fix(integration): teamtailor integration sync template

---

packages/webapp/src/components/TopNavBar.tsx

Fixes NAN-518
- Remove log out from top nav 
It's already in the new user menu bottom left

fix(ui): remove top nav logout

---

packages/webapp/src/pages/Integration/AuthSettings.tsx

align elements

---

packages/webapp/src/components/ui/input/SecretInput.tsx

Copy didn't work for secret input fields
NAN-524

[nan-524] fix copy bug

---

packages/server/lib/clients/auth.client.ts
packages/server/lib/controllers/account.controller.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/environment.controller.ts
packages/server/lib/controllers/flow.controller.ts
packages/server/lib/express.d.ts
packages/server/lib/server.ts
packages/server/tsconfig.json
packages/webapp/src/components/DebugMode.tsx
packages/webapp/src/components/LeftNavBar.tsx
packages/webapp/src/layout/DashboardLayout.tsx
packages/webapp/src/pages/AccountSettings.tsx
packages/webapp/src/pages/AccountSettings/Admin.tsx
packages/webapp/src/store.ts

Fixes NAN-101
- Show if debug mode is activated in the UI
- Move admin action into it's own component
- POST /admin/switch now returns proper json error to display in the UI
- Debug mode expires after 10minutes 
- In `account.controller.ts` modify `AUTH_ENABLED=true` and `AUTH_ADMIN_SWITCH_ENABLED=true`
- In your `.env` add your local `NANGO_ADMIN_UUID`
- Test the feature
I tried something that's easy to read, hard to miss, but easy to not capture in screenshots, let me know.

feat: show debug mode in UI

---

integration-templates/github/github-issues-demo-action.ts
integration-templates/github/nango.yaml

Contributes NAN-522
- Missing input type in the new action

fix(demo): missing input

---

packages/server/lib/controllers/account.controller.ts
packages/server/lib/express.d.ts
packages/server/lib/utils/utils.ts

Follow up of #1831 
For some reason the session was never saved in db in prod. Could not reproduce locally but tested this fix in staging seems to work. Might be due to a race condition in the callbacks
- Manually call save and return only after this

fix(auth): correctly save debug mode in session

---

packages/cli/lib/fixtures/nango-yaml/v2/mixed-literal-model/nango.yaml
packages/cli/lib/services/model.service.ts
packages/cli/lib/sync.unit.test.ts

[nan-560] account for models

---

packages/jobs/lib/app.ts

After last eslint fix, I "broke" this call by adding the await but it's actually not returning

fix(jobs): do not wait for temporal

---

packages/cli/lib/services/dryrun.service.ts
packages/cli/lib/services/model.service.ts
packages/shared/lib/services/nango-config.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/utils.ts

Add more comprehensive check for js/ts objects and fix eslint errors
NAN-560

[nan-560] more comprehensive check

---

packages/shared/lib/services/onboarding.service.ts
packages/shared/lib/utils/analytics.ts
packages/webapp/src/pages/InteractiveDemo/FetchBloc.tsx
packages/webapp/src/pages/InteractiveDemo/index.tsx

- Add missing node event `#6`
- Display an error when we fail to fetch records after running the sync and log to posthog
- Complete is after Action not after clicking the CTA

fix(demo): feedback 2

---

packages/webapp/src/pages/Activity.tsx

Logs order has been broken after #1844 I forgot about the reverse trick. I'll note to improve this behavior with a long term fix.
- Reup logs order

fix(activity): logs order

---

packages/shared/lib/services/nango-config.service.ts
packages/shared/lib/utils/utils.ts

Empty output for an action causes issues when loading the reference. Allow an empty output for an action
NAN-601

[nan-601] allow for null

---

packages/webapp/src/components/LeftNavBar.tsx
packages/webapp/src/hooks/useEnvironment.tsx

Fixes NAN-602
- Fixes env not updating when using the select input

fix(ui): env not updating

---

packages/server/lib/controllers/auth.controller.ts
packages/webapp/src/pages/InviteSignup.tsx
packages/webapp/src/pages/Signin.tsx
packages/webapp/src/pages/Signup.tsx

Keep the domains the same for login

Auth unhide

---

packages/shared/lib/services/flow.service.ts
packages/shared/lib/services/flow.service.unit.test.ts

One last fix hopefully about Shared path. Flows' path was wrong and the error was swallowed. tbh I wish I could just throw but I don't know the full impact of that.
- Fix path
- Add tests
- Add more check at runtime to avoid any more surprises

fix(flows): path + strictness

---

packages/cli/lib/services/dryrun.service.ts
packages/runner/lib/client.unit.test.ts
packages/shared/lib/sdk/sync.ts
packages/shared/lib/services/sync/run.service.ts
packages/webapp/src/utils/utils.tsx

Ouput a summary of records that would be added, updated, or deleted by the integration script
NAN-621

[nan-621] output # of records

---

packages/server/lib/clients/auth.client.ts

Enable local passport strategy for enterprise
NAN-634

[nan-634] enable auth for enterprise too

---

docs-v2/integrate/guides/authorize-an-api.mdx
docs-v2/reference/sdks/frontend.mdx
docs-v2/spec.yaml
packages/frontend/lib/index.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/oauth.controller.ts
packages/shared/lib/models/Auth.ts
packages/shared/lib/models/Webhook.ts
packages/webapp/src/components/ui/input/TagsInput.tsx
packages/webapp/src/pages/Connection/Authorization.tsx
packages/webapp/src/pages/Connection/Create.tsx
packages/webapp/src/pages/Connection/Show.tsx
packages/webapp/src/types.ts

Updates name for the oauth overrides to be more explicit.
- Fix creating a new connection to show right after creation
- Fix deleting a connection to not show right after deletion
NAN=638

(feat) [NAN-638] updated and docs

---

packages/server/lib/controllers/auth.controller.ts
packages/server/lib/controllers/user.controller.ts
packages/webapp/src/components/ui/button/Auth/Google.tsx

Fix few logic errors with the invite flow.
NAN-661

[nan-661] fix invite flow

---

packages/server/lib/clients/auth.client.ts

Strict check for empty password and email address
NAN-645

[nan-645] check for empty

---

dev/docker-compose.dev.yaml
docker-compose.yaml
package-lock.json
packages/server/package.json
packages/shared/package.json

Fixes NAN-663
With the recent Redis license change it's better to pin and see later if this impact us or our customers.

fix(deps): pin redis

---

packages/data-ingestion/lib/index.ts
packages/shared/lib/services/sync/run.service.integration.test.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/services/sync/run.service.unit.test.ts

Add in additional props
NAN-591

[nan-591] lookup account and env name

---

packages/shared/lib/services/sync/run.service.ts

Don't do lookups if in dry run

perform looksups if not dryrun

---

packages/shared/lib/sdk/sync.ts

Pass a generic to triggerAction
NAN-670

allow triggerAction to take and return a generic

---

packages/server/lib/controllers/auth.controller.ts
packages/utils/lib/environment/detection.ts

Use public server url variable instead of faulty replacement logic
NAN-661

[nan-661] use public server url

---

packages/server/lib/controllers/auth.controller.ts

Redirect the user if they cancel the google auth
NAN-649

[nan-649] redirect on error

---

packages/server/lib/controllers/connection.controller.ts
packages/shared/lib/utils/error.ts
packages/webapp/src/pages/Connection/Show.tsx

Fixes NAN-673
- API: unknown_connection error now returns a proper 404
- UI: display a 404 only on this error code

fix(ui): correct 404

---

packages/server/lib/controllers/environment.controller.ts

Not sure how it worked
- Use correct  function to get accountId

fix(login): correct accountId

---

docs-v2/integrations/all/personio.mdx
docs-v2/mint.json
packages/shared/providers.yaml

Add docs with snippet and remove extra param not needed for the provider
NAN-671

[nan-671] documentation for personio

---

Dockerfile
package-lock.json
package.json
packages/records/lib/constants.ts
packages/records/lib/db/client.ts
packages/records/lib/db/config.ts
packages/records/lib/db/migrate.ts
packages/records/lib/db/migrations/20240327151027_create_records_table.ts
packages/records/lib/env.ts
packages/records/lib/helpers/format.ts
packages/records/lib/helpers/uniqueKey.ts
packages/records/lib/helpers/uniqueKey.unit.test.ts
packages/records/lib/index.ts
packages/records/lib/models/records.integration.test.ts
packages/records/lib/models/records.ts
packages/records/lib/types.ts
packages/records/lib/utils/encryption.ts
packages/records/lib/utils/logger.ts
packages/records/lib/vitest.d.ts
packages/records/package.json
packages/records/tsconfig.json
packages/server/package.json
packages/shared/lib/utils/encryption.manager.ts
packages/utils/lib/environment/parse.ts
tests/setup.ts
tsconfig.build.json

Adding the `records`package to interact with nango users records. This package introduces a new table which will be hosted on a different database.
For now the package is not being used, other than running the db migration. Next step will be to use this package to double write the records in both the old table and the new one.

add records package (records migration)

---

packages/server/lib/controllers/access.middleware.ts
packages/server/lib/controllers/account.controller.ts
packages/server/lib/controllers/flow.controller.ts
packages/server/lib/server.ts
packages/shared/lib/db/migrations/20240403100610_add_account_status_info.cjs
packages/shared/lib/models/Admin.ts
packages/shared/lib/services/account.service.ts

Add a way to track customers and manage with a simple API. This is the first step of resource capping as we need to know which customers to cap.
NAN-680

[nan-680] add is_capped and admin only api to edit

---

.eslintignore
.eslintrc
integration-templates/github/github-write-file.ts
packages/server/lib/clients/publisher.client.unit.test.ts
packages/server/lib/controllers/apiAuth.controller.ts
packages/server/lib/controllers/appAuth.controller.ts
packages/server/lib/controllers/appStoreAuth.controller.ts
packages/server/lib/controllers/auth.controller.ts
packages/server/lib/controllers/config.controller.ts
packages/server/lib/controllers/connection.controller.ts
packages/server/lib/controllers/oauth.controller.ts
packages/server/lib/controllers/sync.controller.ts
packages/server/lib/controllers/unauth.controller.ts
packages/server/lib/controllers/webhook.controller.ts
packages/shared/lib/clients/oauth2.client.ts
packages/shared/lib/clients/provider.client.ts
packages/shared/lib/clients/sync.client.ts
packages/shared/lib/integrations/scripts/webhook/slack-webhook-routing.ts
packages/shared/lib/models/Activity.ts
packages/shared/lib/models/Runner.ts
packages/shared/lib/sdk/sync.unit.test.ts
packages/shared/lib/services/connection.service.ts
packages/shared/lib/services/environment.service.ts
packages/shared/lib/services/file/local.service.ts
packages/shared/lib/services/file/remote.service.ts
packages/shared/lib/services/notification/webhook.service.unit.test.ts
packages/shared/lib/services/sync/config/config.service.ts
packages/shared/lib/services/sync/job.service.ts
packages/shared/lib/services/sync/run.service.ts
packages/shared/lib/utils/error.manager.ts

- Fix await/void promises
- Fix some unhandled errors
Down to **4 errors** (and **7385 warnings** 🙈), we can now think about adding it to the CI

fix(eslint): pass #10

---

packages/server/lib/controllers/appAuth.controller.ts
packages/server/lib/controllers/oauth.controller.ts

Contributes to NAN-582 
For the logs I need to add a write at all those places but I don't want to declare error a third time
- Store and reuse error definition where needed

fix(error): reuse errors definition

---

packages/shared/lib/db/migrations/20240404185301_add_sync_last_fetch_at.cjs
packages/shared/lib/models/Sync.ts
packages/shared/lib/services/sync/data/records.service.ts
packages/shared/lib/services/sync/sync.service.ts

Track last fetched date for syncs. Curious @TBonnin how this jives with the work you're doing?
NAN-683

[nan-683] track last fetched time for a sync

---

docs-v2/integrations/all/peopledatalabs.mdx
packages/shared/providers.yaml

Adds peopledatalabs as an integration. Super simple, just an API key.

Adds People Data Labs Auth

---

packages/webapp/src/pages/Connection/Authorization.tsx

Fixes minimalistic connection object
NAN-710

[nan-710] check for connectionConfig

---

packages/node-client/lib/index.ts

Fixes NAN-714
Closes #1970
The casing was incorrectly set to camelCase instead of snake_case

fix(node): wrong casing for modified_after

---

packages/node-client/lib/index.ts

- Fix condition, modifiedAfter was only set if delta was set

fix(node): wrong condition on delta

---

packages/webapp/src/pages/Activity.tsx
packages/webapp/src/pages/Connection/List.tsx
packages/webapp/src/pages/EnvironmentSettings.tsx
packages/webapp/src/utils/language-snippets.tsx

- Fix connect slack icon in the environment settings.
- Alphabetize the integrations and connections on the activity page
- Alphabetize 
NAN-439

[NAN-439] webapp revamp followups finaly

---

packages/jobs/lib/integration.service.ts

runningScripts used to be of type Record<string, context> but was changed to a Map in https://github.com/NangoHQ/nango/commit/8a5520e228cc9cde059c20278c0183c12a71d696 It caused the `Object.keys(this.runningScripts)` to always return an empty array, which means no heartbeat have benn sent in 2 months
https://linear.app/nango/issue/NAN-711/sync-frequency-issue

jobs: fix heartbeat

---

package-lock.json
packages/utils/package.json
scripts/publish.sh

bundleDependencies is causing issues with package resolution in remote environments so dynamically add it to publish
NAN-753

[nan-753] bundle deps dynamically

---

docker-compose.yaml
packages/cli/docker/docker-compose.yaml
packages/persist/Dockerfile
packages/persist/nodemon.json
packages/records/lib/db/migrations/20240327151027_create_records_table.ts
packages/server/Dockerfile
packages/server/lib/migrate.ts
packages/server/lib/server.ts
packages/server/nodemon.json
packages/utils/lib/environment/parse.ts

Setup records db migration so records table will be created. I have also setup the env var in staging and production
Next step will be double writing records in this table in addition to writing them in current table

run records database migration

---

docs-v2/customize/guides/create-a-custom-integration.mdx

Update default action HTTP method in create-a-custom-integration.mdx

---

.eslintrc
.github/workflows/lint.yaml
.github/workflows/tests.yaml
packages/records/lib/models/records.integration.test.ts
packages/shared/lib/integrations/scripts/connection/github-app-oauth-post-connection.ts
packages/shared/lib/models/Activity.ts

Fixes NAN-733
- Added eslint to run on the CI
Only errors are reported
- Optional: Used a github action to add the comments directly to the PR. if you find it too noisy we can run it the classic way (cf: the comment)

fix(ci): add eslint

---

packages/shared/lib/services/config.service.ts

- Type is a string apparently bc of max_safe_integer in JS

fix: type of count is a string

---

packages/cli/docker/docker-compose.yaml

RECORDS_DATABASE_URL must be a valid url. Setting it to the nango-db container as default

docker compose: set valid default value for RECORDS_DATABASE_URL env var

---

docs-v2/sample-app.mdx

- Do not upper case the title
- Fix icon in dark mode
- Add hover

docs: sample app feedback

---

packages/server/lib/controllers/sync.controller.ts

Next step in the records migration: reading from new db. First, we read both legacy and new db, comparing the output and logging discrepancy, still returning the legacy output.
Fetching new records is behind a feature flag so it can easily be enabled/disabled
Once we have confirmed there is no discrepancy, I will make a PR to return the output of new db

fetch new records and compare with legacy ones (still returning legacy)

---

packages/records/lib/helpers/format.ts
packages/shared/lib/services/sync/data/records.service.ts

Not a big deal but records deleted in the same batch could have slightly different deletedAt/updateAt

fix: set same deletedAt/updatedAt for deleted records in the same batch

---

docs-v2/customize/guides/advanced/handle-rate-limits.mdx
docs-v2/customize/guides/advanced/validate-api-responses.mdx
docs-v2/customize/guides/contribute-an-integration-template.mdx
docs-v2/mint.json
docs-v2/reference/limits.mdx

Add guide to handle rate limits

---

docs-v2/customize/guides/advanced/handle-large-datasets.mdx

Mention lastSyncDate in docs

---

dev/docker-compose.dev.yaml
docker-compose.yaml
packages/cli/docker/docker-compose.yaml

- Fix opensearch port
- Fix opensearch security plugin
- Fix missing env
- Fix missing records url
---
NB: opensearch is very long to boot compare to elasticsearch, I need to double check the configuration

fix: docker compose 

---

packages/jobs/lib/tracer.ts
packages/persist/lib/controllers/persist.controller.ts
packages/persist/lib/tracer.ts
packages/server/lib/tracer.ts
packages/utils/lib/environment/parse.ts
packages/utils/lib/environment/parse.unit.test.ts

- Zod can't coerce boolean https://github.com/colinhacks/zod/issues/2985
I only tested with true-ish values, that what's you got when not fuzzing unit test
- Do not log runner logs in Persist
- Trace opensearch in datadog

fix(logs): wrong zod coerce, add tracer

---

docs-v2/introduction.mdx

Video size responsive in docs

---

packages/shared/lib/clients/sync.client.ts
packages/shared/lib/models/NangoConfig.ts
packages/shared/lib/services/sync/config/config.service.ts

Customer reported that a public template that is disabled still kicks off.
NAN-822

[nan-822] check for enabled when creating a connection
