NangoHQ/nango

- src/clients/javascript/package.json
- src/clients/javascript/src/index.ts
- src/clients/javascript/test/connect.test.js
- src/clients/javascript/test/initialization.test.js
Support of Pizzly initialization with `new Pizzly('publishable_key', 'https://example.org')`
> feat: support of Pizzly initialization with a string

- src/lib/database/integrations.ts
- views/assets/css/dashboard.css
- views/dashboard/api-configurations-edit.ejs
- views/dashboard/api-configurations-new.ejs
Fix an issue with adding new scopes on an API configuration.
The scopes are saved in database using an array, where each item is a scope. The issue was that the scopes wered saved using this format:
```js
[
"https://www.googleapis.com/auth/spreadsheets\r",
"https://www.googleapis.com/auth/spreadsheets.readonly"
]
```
Notice the extra `\r`. Updating the `validateConfigurationScopes` fixed the issue.
> fix: support multiple scopes (one per line)

- package.json
- src/routes/proxy.ts
- yarn.lock
Enable all [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) requests on the proxy endpoint. This make the proxy reachable using Pizzly JS, when the Pizzly instance is not located on the same domain than the application.
You might need to update your CORS options to secure your instance. Have a look to the [CORS middleware](https://github.com/expressjs/cors) documentation to learn how to do it.
> fix: enable cors on proxy

- src/clients/javascript/README.md
Setup in readme for pizzly-js is missing the `new` keyword.
> [pizzly-js] Add missing new keyword to readme

- Dockerfile
When deploying the Docker image to production, we realized that the views directory was not copied into the dist dir.  
This PR adds the views explicitly to the resulting image.
> fix: add views directory to the docker image

- src/lib/proxy/index.ts
This PR adds support for a case insensitive prefix for headers that should be forwarded. 
Somewhere in our stack, our headers got lowercased. This PR makes sure that Pizzly can handle that.
Caveats:
- Not tested - although I could not find tests for the rest of the module either.
- It might be a naive implementation, but it works for us 😄 
Have a great weekend!
> allow for case insensitive proxy forward headers

- integrations/xero.json
OAuth1 has been deprecated by Xero since Feb 2020:
https://devblog.xero.com/an-update-on-why-we-are-saying-goodbye-oauth-1-0a-hello-oauth-2-0-6a839230908f
Here's a PR to support OAuth 2. Our app didn't actually work (mentioned #63) with OAuth1 because it was made in March!
I had to change the baseURL to `https://api.xero.com` rather than the previous `https://api.xero.com/api.xro/2.0/`.
Xero requires a `xero-tenant-id` header to be passed with subsequent requests to gain access to business accounts the user has access to.
The only way to get this `xero-tenant-id` is to query:
`GET https://api.xero.com/connections`
Then after obtaining the tenant ID you can query:
`GET https://api.xero.com/api.xro/2.0/...` with an added header `xero-tenant-id: "abcdefg-12345"`.
Question: Is there an …
> Update Xero integration from OAuth1 to OAuth2

- src/clients/javascript/package.json
- src/clients/javascript/src/connect.ts
Following issue #75, it appeared that SmartPension API triggers some postMessage events within the authorization modal. It's something that wasn't anticipated by `pizzly-js`, which was reacting to any single events that it received from the modal. 
This PR make sure that only the messages having the same origin than the the callback URL are processed.
> Force Pizzly-js to listen to the right events

- src/routes/dashboard.ts
- views/assets/js/dashboard.js
Thanks @gotbadger for reporting this bug. The trash icon wasn't deleting an authentication (or configuration) when the Pizzly instance was protected behing a secretKey. Now it does.
> Fix an issue with the trash icon on the dashboard

- src/clients/javascript/src/connect.ts
- src/clients/javascript/src/types.ts
Adds any fields added to a `params` field in the options object, when connecting to the upstream API. This follows the assumptions made on the server side that additional params can be passed in this way.
No tests were added here, but the upsteam did not test the method anyway.
> fix (client): handle param options

- integrations/moltin.json
- integrations/snov.json
- src/legacy/auth/v3/strategies/oauth2/client-credentials.ts
Looks like the `ClientCredentials` strategy for OAuth 2.0 was not well-handled during the open-source migration. Only two APIs (Snov.io and Moltin) are concerned. That's probably the reason why this hasn't been detected sooner.
Also the configuration for Snov.io was not well-made. This has been fixed and tested (manually).
We definitely need better logging in all aspects, as well as tests on the API integrations.
> fix: APIs using client_credentials as grant type

- src/lib/error-handling/index.ts
- src/lib/oauth/index.ts
- src/lib/proxy/index.ts
- src/routes/api.ts
Improve the error message when trying to refresh an authentication but there's none refreshToken saved (see feedback in #173). The new error message in that case would be:
```json
{"error":{"type":"token_refresh_missing","message":"Unable to refresh the token. That user has no refresh token. The API might have not providing one."}}
```
> feat: improve error message on token refreshness

- src/legacy/auth/v3/strategies/oauth2/auth-code.ts
Should resolve #191 and issues with APIs that don't require scopes.
> Swap scope non-null operator to optional operator

- docs/auth.md
Correct markdown url by adding `https` prefix
Click on `Google Cloud Console` link in README causes 404 not found error. Adding `https` scheme fixes the problem.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> FIX: Invalid Google cloud URL

- src/clients/node/package.json
- src/clients/node/tsconfig.json
Updates the node client's tsconfig to support issue #220, adds strict mode, and updates the package file with the correct url.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> Add typing to node client

- app.json
- integrations/slack.json
- src/lib/proxy/index.ts
Originally the MailChimp request URL used a fixed value "https://server.api.mailchimp.com/3.0/". This request URL doesn't exist so the request will fail. According to MC's docs, the server in the request URL should be the user's data center in use, for example, us2 and us6. So only something like https://us1.api.mailchimp.com/3.0/ will work.
The committed change in the proxy module tries to read a "Chimp-Dc" header, and if it exists, it will try to replace the "server" in the request value with the value provided by the "Chimp-Dc" header (for example, us1).
Also upgraded Slack Auth version from v1 to v2
> fixed MailChimp request URL bug

- packages/server/lib/utils/utils.ts
In order to address the issue described here:
https://github.com/NangoHQ/Pizzly/issues/279
For a production deployment, where a single machine serves both pizzly and a web-app, it's not ideal to have to open two separate ports (one for pizzly, one for the app). Instead, a proxy can redirect traffic to the /oauth route towards pizzly. In those instances, it's helpful to customize the callback URL to point it to the proxy server.
> Enable custom callback URL through an environment variable

- packages/frontend/package.json
The `packages/frontend/package.json` was missing the typings key
> Added typings to the frontend package.json

- packages/auth/lib/controllers/oauth.controller.ts
- packages/auth/providers.yaml
I have tested the OAuth flow and can confirm that it works.
Additionally, `simpleOAuthClient.getToken()` in `oauth2Callback` can throw an Error object which can't be JSON.stringified. It was crashing the server. Now I check if the caught error is an Error and produce a different error output.
> Added Airtable provider

- packages/auth/providers.yaml
- packages/frontend/bin/sample.html
I have tested the OAuth flow and can confirm that it works.
To test it using the frontend, I added an additional field to the bin/sample page that has JSON you can fill in.
- Leaving it as an empty object (the default) will work with all providers that don't require any custom connection params
- Setting it to `{ "subdomain": "whatever" }` will allow Zendesk and Shopify to be tested easily.
> Integration shopify

- packages/auth/providers.yaml
Adds a provider config for [DigitalOcean](https://www.digitalocean.com/).
Links:
* Our ([OAuth docs](https://docs.digitalocean.com/reference/api/oauth-api/)),
* [New OAuth application page](https://cloud.digitalocean.com/account/api/applications/new) requires that the user is logged into their DigitalOcean account.
I've tested this locally and confirmed that it works as expected.
> Add DigitalOcean provider

- docker-compose.yaml
- docs/docs/contribute-api.md
- packages/frontend/bin/Dockerfile
Hey Yall!
I've enjoyed adding the Stripe provider. PR for that coming soon. I did make some tweaks to how the Nango Server is running locally which I think makes it easier for folks to contribute new provider templates.
I updated the docs to reflect the changes, but to summarize...
1. Updated the docker-compsose.yaml so the providers.yaml is synced between host and running docker container
2. Added another running container for the frontend test website
So now instead of running docker compse up, stopping the server, navigating to the server folder and running it locally, then in another shell window running the frontend test site with a python simple server also on the local machine.... it is all just done with the one `docker compose up` command.
This worked well for me. Let me know if …
> Simplify provider contributions

- packages/auth/lib/services/connection.service.ts
- packages/auth/providers.yaml
Stripe returns a refresh token but no expiration info. The access token does not expire but a user can revoke it.
https://stripe.com/docs/connect/oauth-reference#post-token-response
Currently Nango checks for refresh token with expires_at in two places, one which logs it and the other which throws an error. I modified the spot that throws the error to just repeat the log. Silly to duplicate the logging but wanted to at least open the PR for discussion as this is one of the integrations I'd like the most.
if removing that exception doesn't work for some reason...
Some sort of flag that gets passed through from the provider template into the `checkCredentials` call.
```
stripe:
auth_mode: OAUTH2
authorization_url: https://connect.stripe.com/oauth/authorize
token_url: …
```
> Add stripe + ignore issue with refreshtoken/expat

- docs/docs/providers/github.md
I spent too long trying to figure it out that Github API requires `user-agent` header to exist to work. Hope this saves some time from others.
> Add GitHub API gotcha

- docs/docs/providers/zapier-nla.md
- packages/server/providers.yaml
Oauth2 provider for Zapier NLA
Zapier recently released an API for natural language actions
- https://zapier.com/l/natural-language-actions
- https://nla.zapier.com/api/v1/docs
> Add Zapier NLA Provider

- .gitignore
- docker-compose.yaml
**What this PR does**
This PR adds a docker volume in the docker-compose for the Postgres service, this will allow the persistence of the configuration even if the service is restarted.
**Which issue does this solve**
[Here](https://github.com/NangoHQ/nango/issues/372)
> perf: ⚡️ added docker volume to the postgres in docker-compose

- packages/webapp/src/pages/ConnectionList.tsx
This PR encodes the user-provided IDs in the URL. The error happens if you have a slash in your connection ID, e.g., `tea_2MSb8jd6VDptcAcVJuPcJhte3Yc/calendly`, then the redirect doesn't work.
The fix is to redirect a user to https://app.nango.dev/connection/calendly/tea_2MSb8jd6VDptcAcVJuPcJhte3Yc%2Fcalendly instead of https://app.nango.dev/connection/calendly/tea_2MSb8jd6VDptcAcVJuPcJhte3Yc/calendly.
Link to Slack: https://nango-community.slack.com/archives/C04ABR352H0/p1680077423232399
> fix(app): Encode URLs when redirecting

- docs/docs/contribute-api.md
- packages/server/lib/clients/oauth2.client.ts
- packages/server/lib/models.ts
- packages/server/lib/services/connection.service.ts
**Description**
We use the same grant type to request access tokens when we refresh them as we do when we initially request them. For example, we use "authorization_code" as the value for the "grant_type" key in the query parameters when requesting access tokens. We do the same thing for refreshing tokens. However, this does not follow the OAuth 2.0 standard.
**What this PR does**
This PR updates the provider template to add refresh parameters. If the request parameters are not provided, it defaults to the token parameters.
**Issue**
Solves the issue [here](https://github.com/NangoHQ/nango/issues/429)
> fix: Bad request request when requesting for refresh token

- packages/node-client/lib/index.ts
- packages/server/lib/controllers/connection.controller.ts
- packages/server/lib/services/connection.service.ts
- packages/server/providers.yaml
**Discription**
This PR adds a new query parameter, `instant_refresh`, when obtaining a connection. When set to true, this parameter allows for the immediate creation of a fresh refresh token from the provider, bypassing the need to wait for the access token to expire.
> refactor: Add support for querying an immediate refresh of the provider's refresh token

- packages/server/lib/controllers/config.controller.ts
- packages/server/providers.yaml
During development, it's possible that integration has already been created for a provider. However, if the pull request (PR) is not merged and the developer changes their branch, this integration will exist on their database but not on the provider yaml template. This will cause a 500 error when attempting to render the integrations page.
To address this issue, this PR adds a conditional check to parseConnectionConfigParamsFromTemplate to verify if the template exists.
> Fix: connection config params

- docker-compose.yaml
- docs/docs/quickstart.md
Fixes [issue](https://github.com/NangoHQ/nango/issues/495)
> fix: Allow use of dynamic port for Nango DB in docker compose.

- docs/docs/providers/payfit.md
- docs/sidebars.js
- packages/server/providers.yaml
[Issue](https://github.com/NangoHQ/nango/issues/418)
> feat: Add provider for  Payfit

- packages/server/providers.yaml
During a random QA, I found this issue here.
> fix: Mural authorization URL.

- packages/frontend/lib/index.ts
closes #335
This PR make's the `@nango/frontend` sdk compatible with SSR, I've gone through the sdk's code and I don't think we should be doing a `window` object check as we are doing nothing with window object while initlizing. More over all the actions that might need access to `window` are only executed only when your interact with UI on the client side.
PS: Tested in a NextJS project.
Thanks :)
> fix: make frontend sdk ssr friendly

- packages/webapp/src/env.d.ts
- packages/webapp/src/utils/utils.tsx
By declaring these properties in the `ProcessEnv` interface, the TypeScript compiler can ensure that the environment variables used in the code are correctly typed and have the expected values with complete typesafety.
> fully typesafe envs without more work!

- docker-compose.yaml
* Any .env files will get picked up by docker compose automatically so there shouldn't be a need to explicitly specify an `env_file`. If there were multiple files or there was some override logic then that env_file specification could/should be used
* Added https://github.com/NangoHQ/nango/pull/575 as well to verify this doesn't happen moving forward. BTW the Github actions added I believe need to be added as pre merge checks within this repo for them to show below
Let me know if I'm missing something here!
> [Github Issue #572] remove env req as it shouldn't be required

- packages/webapp/src/components/ui/SecretInput.tsx
This PR fixes the overflow effect caused by long inputs in `SecretInput` component.
> fix: input overlaps

- packages/webapp/src/pages/ConnectionCreate.tsx
When a request to create a connection fails, the error message is not shown, and instead a "connection created!" success toast message is displayed.
This happens because the error is caught, handled, and then the success path is executed anyway.
This change reorders the catch block so that the success path is not executed in the case of any errors.
> fix: correctly display error message when creating a connection

- packages/server/lib/controllers/connection.controller.ts
Issue: https://github.com/NangoHQ/nango/issues/643
After conversation with @bastienbeurier added the parameter as he suggested.
This would be a "breaking change" as it would result people that use the refresh token itself to not have this available anymore as the default value is set to false making the refresh token not be sent anymore.
> Api Feature add param refresh_token -> option to not include refresh token in response

- packages/server/lib/migrate.ts
- packages/server/lib/server.ts
- packages/server/lib/utils/migrate.ts
Currently the Nango server performs the database migration at process startup before it starts accepting API calls. If you want to run multiple instances of Nango server for high availability purposes, then this is not ideal as those instances may attempt to perform the database migration at the same time, which can lead to random failures and corruption.
This change keeps the existing behaviour, but introduces a new flag `NANGO_MIGRATE_AT_START`, which when set to `false` will stop the database migration from happening at process startup.
Instead, the database migration can be explicitly run by running `node packages/server/dist/migrate.js`. This should be done once and once only before the Nango server instances are started. My intention is to run this from a Helm pre-install hook.
> feat: add separate command to migrate database

- docs-v2/integrations/all/zendesk.mdx
The old docs references the Zendesk Sales CRM API, which is a different API/oAuth app setup (which [doesn't work with Nango](https://nango-community.slack.com/archives/C04ABR352H0/p1686683332907549) atm)
I'm _pretty sure_ I've got good links for everything, but the Zendesk docs are kinda all over the place, so probably some improvement potential.
> Fix Zendesk documentation

- package-lock.json
- packages/cli/docker/docker-compose.yaml
- packages/cli/package.json
- packages/frontend/lib/index.ts
- packages/frontend/package.json
- packages/node-client/package.json
- packages/server/lib/controllers/oauth.controller.ts
- packages/server/package.json
- packages/shared/package.json
- packages/webapp/package-lock.json
- packages/webapp/package.json
- packages/webapp/src/components/ui/input/TagsInput.tsx
- packages/webapp/src/pages/ConnectionCreate.tsx
- packages/webapp/tsconfig.json
- packages/worker/package.json
Resolves #680 
* Adds the slack specific "User Scopes" option in the connection
* Updates the TagInput component to allow overrides for the `useSet` implementation so the scopes state can be tracked in the parent component
* Adjusts the frontend to push the user scope if provided and update the `ConnectionConfig` to have the optional `user_scope` type
* Updates the oauth controller to parse the user_scope query and set it to the `session.connectionConfig` so that it saves to the database. Puts the user_scope in the `additionalAuthParams` object
> [Github #680] user scope

- packages/shared/lib/services/connection.service.ts
Currently, the `ConnectionService.importConnection` method performs a check using a call to `ConnectionService.getConnection` to ensure that a connection does **not** currently exist. However,  `ConnectionService.getConnection` throws an error if the connection is not found, rather than a null value. `ConnectionService.importConnection` does not expect this, and thus the same error is thrown in that method as well.
This fix will allow for connections to be imported as intended.
> Update import connection check to not throw unncessarily

- .env.example
- docs-v2/sdks/frontend.mdx
- docs-v2/self-host/instructions.mdx
- packages/frontend/lib/index.ts
- packages/server/lib/controllers/account.controller.ts
- packages/server/lib/server.ts
- packages/shared/lib/models/Admin.ts
- packages/shared/lib/utils/utils.ts
- packages/webapp/src/pages/ConnectionCreate.tsx
The websockets path is currently hardcoded to `/` which makes it hard to firewall or otherwise filter requests to the dashboard (which should be very secure) from requests to the websockets (which must be open to non-dashboard users).  This PR allows the websockets server to listen on a different path to allow them to be isolatd from each other, to fix nangohq/nango#677
This adds:
- `NANGO_SERVER_WEBSOCKETS_PATH` to the server's (optional) environment variables.  This defaults to `/` for backwards compatibility.  If set the websockets server only handles that path (and below).
- `websocketsPath` as an optional config parameter to the frontend `Nango` component. This defaults to `/` for backwards compatibility.
- update to the `/api/v1/account` request to optionally include …
> NANGO-677: Allow the websockets path to be configured

- docker-compose.yaml
- docs-v2/contribute.mdx
Detected following a thread with a contributor struggling to run the `/contribute` tutorial [on the community](https://nango-community.slack.com/archives/C04ABR352H0/p1688561037848479).
The `/contrbiute` docs tutorial was broken because it uses the CLI's `docker-compose.yaml` file which does no link to the local `providers.yaml` file. So editing the `providers.yaml` would not be reflected when running `nango start`. 
In general, I think we should remove Docker-related capabilities from the nango CLI. This separates concerns nicely: 
- The CLI is used by non-contributors and doesn't need to know about Docker
- Contributors download the `nango` folder and run Docker commands directly, without the help of the CLI
I re-introduced the `nango` folder root-level `docker-compose.yaml`, linked to …
> Fix contribute tutorial

- packages/server/lib/controllers/oauth.controller.ts
- packages/shared/lib/services/sync/sync.service.ts
@bastienbeurier figured out this dupe issue.
If a connection id is created again that has the same string already it would initiate another sync because the oauth flow was initiated again. This PR checks for an existing sync and returns null if it already exists so another sync isn't initiated.
Remaining item is to stop and delete some duplicate syncs that exist in the system now.
> [gh-#791] await initiate and return null if sync exists

- packages/shared/providers.yaml
Hi!
I noticed today that the dropbox integration is not using a refresh token. According to the [Dropbox API documentation](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token:~:text=token_access_type%20String%3F,to%20online.), authorization requests must be made with `token_access_type=offline` to work. 
Specifically, in their [oauth guide](https://developers.dropbox.com/oauth-guide):
> Note: you’ll need to include token_access_type=offline as a parameter on your Authorization URL in order to return a refresh_token inside your access token payload.
I confirmed that, with the current `providers.yaml` config for dropbox, requests of the form `http://localhost:3003/connection/test-connection-id3?provider_config_key=dropbox-development&refresh_token=true&force_ref …
> dropbox requires token_access_type=offline for refresh token

- integration-templates/hubspot/hubspot-owner.ts
- integration-templates/hubspot/hubspot-user.ts
- integration-templates/hubspot/nango.yaml
Tested in my Nango Dev environment;
```
nango deploy dev
Compiled "./hubspot-owner.ts" successfully
Compiled "./hubspot-service-ticket.ts" successfully
Compiled "./hubspot-user.ts" successfully
Compiled "./models.ts" successfully
{
"newSyncs": [],
"deletedSyncs": []
}
Do you want to continue y/n? y
Successfully deployed the syncs: hubspot-service-ticket@v4, hubspot-owner@v3, hubspot-user@v2!
```
Syncs have ran successfully after a manual trigger;
> Added Owner and User sync for Hubspot

- packages/server/lib/controllers/proxy.controller.ts
- packages/shared/lib/models/Provider.ts
- packages/shared/providers.yaml
Resolves #930 
* Adds a `proxy.retry.at || proxy.retry.after` property to the providers.yaml
* During the retry logic the exponential backoff will first look for an existing `proxy.retry` property in the template and if it exists will wait for that parsed value before the exponential backoff
* Also adds `requestHeaders` and `responseHeaders` to the failed response
> [gh-#930] add retry after header

- packages/server/lib/utils/utils.ts
- packages/server/lib/utils/utils.unit.test.ts
- packages/shared/providers.yaml
Resolves #1026
Adds:
This was put in the `connectionConfig` with this in mind https://www.notion.so/nangohq/August-2023-Metadata-consolidation-edbfc7b8dab64cfea21ab60fce809299?pvs=4.
If the user wants to grab the content they can run a getConnection call and then grab the connection_config:
```
const connection = await nango.getConnection()
const url = connection.connection_config['webhhook.url']
```
> [Github #1026] slack webhook capture

- packages/frontend/lib/index.ts
- packages/server/lib/controllers/oauth.controller.ts
- packages/server/lib/utils/utils.ts
- packages/server/lib/utils/utils.unit.test.ts
Auth params defined in the `providers.yaml` templates can be overriden by the frontend `nango.auth` call. Template auth params can even be removed from the frontend, by setting the given param to `undefined`: 
```js
nango.auth('google', 'test-connection-id', { authorization_params: { prompt: undefined } });
```
> [gh-#1040] Override auth params from nango.auth

- integration-templates/salesforce/salesforce-articles.ts
There were two `WHERE` clauses in the sample query.
> Fix Salesforce articles SOQL query

- packages/server/lib/controllers/sync.controller.ts
- packages/shared/lib/clients/sync.client.ts
- packages/shared/lib/db/migrations/20230928133211_activity_log_session_id_index.cjs
- packages/shared/lib/services/activity/activity.service.ts
- packages/shared/lib/services/nango-config.service.ts
- packages/shared/lib/services/nango-config.service.unit.test.ts
- packages/shared/lib/services/sync/orchestrator.service.ts
- packages/shared/lib/services/sync/run.service.ts
- packages/shared/lib/services/sync/schedule.service.ts
- packages/shared/lib/services/sync/sync.service.ts
- packages/shared/lib/utils/error.ts
- packages/webapp/src/pages/ConnectionDetails.tsx
Resolves #1036 
* link activity log id again by session_id and add index 
* Clean up error state display on connection details 
* add sync_config_id earlier in the run service for proper linking
* Adds additional unit tests to the config interval and offset methods
> [gh-#1036] unpause sync starts right away and adjusts the offset

- packages/shared/lib/services/sync/data/data.service.ts
- packages/shared/lib/services/sync/data/delete.service.ts
- packages/shared/lib/services/sync/data/records.service.ts
> [Github #1094] track deletes updates

- packages/shared/providers.yaml
The base_url subdomain variable was missing the $ prefix.
> Fixed Shopify subdomain variable

- docs-v2/sdks/node.mdx
- packages/cli/lib/sync.ts
- packages/shared/lib/services/nango-config.service.ts
- packages/shared/lib/services/sync/config/config.service.ts
- packages/webapp/src/utils/utils.tsx
Resolves #1176 
Also fixes
* Minor `getEnvironmentVariables` documentation issue
* Sync runtime display when there is only milliseconds
Exported object and from the REST API looks like:
```
[
{
"providerConfigKey": "github",
"syncs": [],
"actions": [
{
"name": "github-list-repos-action",
"type": "action",
"runs": null,
"track_deletes": false,
"auto_start": true,
"attributes": {},
"returns": [
"GithubRepo"
],
"models": [
{
"name": "GithubRepo",
"fields": []
}
],
"description": "",
"scopes": []
}
]
},
{
"providerConfigKey": "notion-pages",
"syncs": [
{
"name": "notion-pages",
"type": "sync",
"runs": "every day",
"track_deletes": true,
"auto_start": true,
"attributes": {},
"returns": [
"Document"
],
"models": [
{
"name": "Document",
"fields": [
{
"name": "id",
"type": "string"
},
{
"name": …
```
> [Github #1176] exportable object

- packages/cli/lib/index.ts
- packages/cli/lib/sync.ts
- packages/node-client/lib/types.ts
- packages/shared/lib/models/Connection.ts
- packages/shared/lib/sdk/sync.ts
- packages/shared/lib/services/sync/run.service.ts
Resolves #1022 
```
There are 28 logs messages remaining. Would you like to see the next 10 log messages? (y/n)
```
Resolves #1020 
```
(base) ➜  nango-integrations npx nango dryrun -h                                       
Usage: nango dryrun [options] <name> <connection_id>
Dry run the sync|action process to help with debugging against an existing connection in cloud.
Options:
--auto-confirm                     Auto confirm yes to all prompts.
--debug                            Run cli in debug mode, outputting verbose logs.
-e [environment]                   The Nango environment, defaults to dev. (default: "dev")
-l, --lastSyncDate [lastSyncDate]  Optional (for syncs only): last sync date to retrieve records greater than this date
-i, --input [input]                Optional (for …
```
> [Github #1022] dryrun log messages

- packages/cli/lib/sync.ts
- packages/cli/lib/utils.ts
- packages/node-client/lib/index.ts
- packages/server/lib/controllers/connection.controller.ts
- packages/server/lib/controllers/environment.controller.ts
- packages/server/lib/controllers/proxy.controller.ts
- packages/server/lib/server.ts
- packages/shared/lib/clients/sync.client.ts
- packages/shared/lib/db/migrations/20231027135906_slack_notifications_option.cjs
- packages/shared/lib/db/migrations/20231030112937_slack_notifications_table.cjs
- packages/shared/lib/index.ts
- packages/shared/lib/models/Environment.ts
- packages/shared/lib/models/SlackNotification.ts
- packages/shared/lib/services/account.service.ts
- packages/shared/lib/services/environment.service.ts
- packages/shared/lib/services/nango-config.service.ts
- packages/shared/lib/services/notification.service.ts
- packages/shared/lib/services/sync/config/config.service.ts
- packages/shared/lib/services/sync/notification/slack.service.ts
- packages/shared/lib/services/sync/notification/webhook.service.ts
- packages/shared/lib/services/sync/run.service.ts
- packages/shared/providers.yaml
- packages/webapp/src/components/ui/button/Button.tsx
- packages/webapp/src/components/ui/input/SecretInput.tsx
- packages/webapp/src/pages/Activity.tsx
- packages/webapp/src/pages/ConnectionCreate.tsx
- packages/webapp/src/pages/ProjectSettings.tsx
Resolves #1192 
Resolves #1151 
* Allows users to set up Slack notifications for failing syncs
> [Github #1192] slack alerts

- packages/server/lib/controllers/connection.controller.ts
- packages/shared/lib/index.ts
- packages/shared/lib/services/sync/notification/slack.service.ts
- packages/webapp/src/components/LeftNavBar.tsx
* Edge case handled if a user installs the slack app has an open notification, then uninstalls and then installs again on a new channel the open notification would try to attach to the old channel
> [Github #1211] close open slack notifications on uninstall

- docs-v2/integrations/all/microsoft-tenant-specific.mdx
- docs-v2/integrations/erp.mdx
- docs-v2/mint.json
- packages/shared/providers.yaml
The `microsoft-teams` provider works for shared/saas Microsoft services that are in the `common` tenant.  This provider is essentially the same but allows the `tenant` to be provided as a Frontend SDK additional config parameter so that any tenant can be accessed.
This is required for services that are tenant specific and are not available in the general `common` tenant as the tenant id can be a random value.
This has been added as a new provider rather than changing the existing `microsoft-teams` one so as not to break backwards compatibility for users of that one.  This new provider also does not provide any sync configuration as it is unknown which service will be behind the Azure app registration so there isn't anything consistent to sync.
See the docs update included with the PR for …
> Add support for Microsoft tenant-specific endpoints

- packages/frontend/lib/index.ts
- packages/node-client/lib/index.ts
- packages/webapp/src/pages/IntegrationCreate.tsx
Resolves #1276 
- Export `RecordMetadata` in case users want to use that type for the `getRecords` response
- Small tweak to the info icon to be the correct size
> [Github #1276] fix create call

- integration-templates/slack/nango.yaml
- integration-templates/slack/slack-channels.ts
- integration-templates/slack/slack-messages.ts
Added description for all Slack syncs to `nango.yaml`
Improved/fixed Slack channels sync:
`slack-channels` sync now only auto-joins all public channels if `joinPublicChannels` is set to true in the metadata.
Technically, this is a breaking change, but after a quick check by @khaliqgant, this doesn't seem to be used by anybody in production.
=> resolves #1167 
Improved the slack messages sync:
- Stores last sync date per channel: Upon detection of a new channel, a full refresh is done. Afterward, incremental sync of the last 10 days.
- If a channel no longer shows up, it removes it from the metadata of synced channels (but does not delete any existing records). This way, if it shows up again, a full refresh sync is done again.
- Uses new `nango.paginate`
- Centralizes saving of message and …
> Improve pre-built Slack syncs

- .yamllint
- docs-v2/spec.yaml
- packages/frontend/lib/index.ts
- packages/server/lib/clients/web-socket.client.ts
There is a race condition that could lead to the `The authorization window was closed before the authorization flow ` error if processing the success message coming from the server takes longer than closing the popup window and check if the window is closed
This fix ensure that the message sent by the server to the frontend via websocket is received and processed before returning the html
> [gh-1251] send html to close window after message is processed

- packages/server/lib/clients/web-socket.client.ts
There is a possibility that the frontend doesn't connect to the websocket server fast enough (aka before the server sends the notifySuccess/Error). In this case the success/error message is never send.
This commit adds logging in notifySuccess/Err to test this theory and confirm if the server successfully sends those websocket messages
That would explain why this bug is not reproducible locally since the websocket connection would be really fast unlike in prod where the connection has to go through the internet :)
> frontend: adding logs to debug why Nango.auth() sometimes doesn't resolve

- .yamllint
A lot of yaml files (integrations templates or spec.yaml) have long lines (ex: description). Disabling the yamlllint line-length rule since it is not very meaningful
> disable yamllint line-length rule

- packages/shared/lib/services/environment.service.ts
- packages/shared/lib/services/environment.service.unit.test.ts
environment service is now fetching from the db if env is not cached yet. 
This allows server to load environment that would have been created after it started
#1295
> enviornment srv: fetch env from db if not in cache

- packages/shared/lib/services/connection.service.ts
- packages/shared/lib/utils/kvstore/InMemoryStore.ts
- packages/shared/lib/utils/kvstore/InMemoryStore.unit.test.ts
- packages/shared/lib/utils/kvstore/KVStore.ts
- packages/shared/lib/utils/kvstore/RedisStore.ts
- packages/shared/lib/utils/lock/locking.ts
- packages/shared/lib/utils/lock/locking.unit.test.ts
The goal is to make sure that multiple request to refresh the oauth token are not conflicting and overriding each other. The implementation is using Redis to add a lock around the oauth token refresh logic
Third part of https://www.notion.so/nangohq/Nov-2023-Server-Horizontal-Scaling-209359b01bac4457aaba95a4eb8d3b5a
> Prevent multiple oauth token refresh to occur at the same time

- packages/cli/lib/services/local-integration.service.ts
- packages/shared/lib/models/Sync.ts
- packages/shared/lib/services/sync/run.service.ts
- packages/worker/lib/activities.ts
- packages/worker/lib/integration.service.ts
- packages/worker/lib/workflows.ts
For each sync store the syncId and temporal context in memory and send a heartbeat every 5 minutes. Set temporal to timeout if a heartbeat is not received within 30 minutes
NAN-76
> [NAN-76] sync heartbeat to know when a sync or action has stalled

- packages/shared/providers.yaml
With the prompt parameter set to 'consent', an user would always be asked to allow access to given SF app, even if they are already logged in.
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_web_server_flow.htm&type=5
Resolved #1371
> salesforce integration: add prompt=consent ouath parameter

- packages/node-client/lib/index.ts
The [controller](https://github.com/NangoHQ/nango/blob/a910b15da8481c94e71c3c3ec1d6284e7b305b2c/packages/server/lib/controllers/config.controller.ts#L147C41-L147C41) returns `configs`, this change corrects to match the server.
No issue
> Correct return type for listIntegrations

- packages/shared/lib/db/migrations/20231205184840_records_composite_index.cjs
Adds a composite index on the `['nango_connection_id', 'model', 'created_at', 'id']` field to improve the `order by`. Note that this migration runs using concurrently as to not lock the table when performing the migration. This table has a lot of active writes since syncs write to it frequently.
NAN-103
> [nan-103] add composite index

- docs-v2/integrations/all/paypal.mdx
- docs-v2/integrations/payment.mdx
- docs-v2/mint.json
- packages/shared/providers.yaml
- packages/webapp/public/images/template-logos/paypal-sandbox.svg
- packages/webapp/public/images/template-logos/paypal.svg
##Describe your changes
- Added configuration for paypal and paypal-sandbox in providers.yaml
- Added paypal and paypal-sandbox to docs-v2.
- Added paypal pages for Supported API groups in mint.json.
- Added paypal SVG files in template-logos folder.
- Consolidate Paypal docs pages
This provider has been used successfully in local development to connect to Paypal/Paypal-sandbox and successfully call those endpoints after authorizing using Nango.
The documentation update was reviewed using ```npm run docs``` and verifying on localhost.
> Add support for paypal and paypal-sandbox endpoints

- packages/shared/lib/index.ts
- packages/shared/lib/utils/featureflags.ts
- packages/shared/lib/utils/kvstore/InMemoryStore.ts
- packages/shared/lib/utils/kvstore/InMemoryStore.unit.test.ts
- packages/shared/lib/utils/kvstore/KVStore.ts
- packages/shared/lib/utils/kvstore/RedisStore.ts
It checks if a key exists in Redis. If key exists, then flag is enabled 
3rd param is the fallback value if key existence cannot be determined. 
4th optional param allows to make a reversed flag (aka: will be enable if the key DOESN'T exist)
how to use it:
```
const flag = await featureFlags.isEnabled('FLAG_NAME', DISTINCT_ID, false);
```
To create the key in redis use `redis-cli`
```
// set the key
SET flag:FLAG_NAME:DISTINCT_ID 1
// delete the key
DEL flag:FLAG_NAME:DISTINCT_ID
```
https://www.notion.so/nangohq/Feature-flags-a20349a27ad644aa912b161b7558c459
> add feature flag feature

- docs-v2/integrations/all/okta.mdx
- docs-v2/integrations/other.mdx
- docs-v2/mint.json
- packages/shared/providers.yaml
- packages/webapp/public/images/template-logos/okta.svg
##Describe your changes
Resolves #1367
- Added configuration for okta in providers.yaml
- Added okta to docs-v2.
- Added okta pages for Supported API groups in mint.json.
- Added okta SVG file in template-logos folder.
- Consolidate Okta docs pages
##Test
This provider has been used successfully in local development to connect to Okta and successfully call those endpoints after authorizing using Nango.
The documentation update was reviewed using ```npm run docs``` and verifying on localhost.
> Add support for Okta (service APIs)

- docs-v2/integrations/all/auth0.mdx
- docs-v2/integrations/other.mdx
- docs-v2/mint.json
- packages/shared/providers.yaml
- packages/webapp/public/images/template-logos/auth0.svg
##Describe your changes
- Added configuration for auth0 in providers.yaml
- Added auth0 to docs-v2.
- Added auth0 pages for Supported API groups in mint.json.
- Added auth0 SVG file in template-logos folder.
- Consolidate Auth0 docs pages
##Test
This provider has been used successfully in local development to connect to Auth0 and successfully call those endpoints after authorizing using Nango.
The documentation update was reviewed using ```npm run docs``` and verifying on localhost.
> Add support for Auth0 APIs

- packages/shared/lib/db/migrations/20231213124728_drop_sync_data_records_indexes.cjs
Used the query described in the following blog post to determine which indexes are not (or rarely) used
http://www.databasesoup.com/2014/05/new-finding-unused-indexes-query.html
Those indexes have size > 10Mb and are on write-heavy tables. The goal with dropping those indexes is to lower the pressure on the database when writing into those tables.
> Drop indexes for table sync_data_records that are not/little used

- packages/shared/lib/sdk/sync.ts
`setMetadata` sdk function had the wrong type. It can accept any object not just string
> sdk: fix setMetadata argument type

- package-lock.json
- package.json
- packages/jobs/nodemon.json
- packages/jobs/package.json
- packages/runner/.gitignore
- packages/runner/nodemon.json
- packages/server/nodemon.json
- packages/server/package.json
- packages/shared/package.json
- packages/worker/nodemon.json
- packages/worker/package.json
Adds gitignore and uses `tsx` instead of `ts-node`. With a new computer ts-node refuses to start and based on some threads this seems to be a common issue. 
```
[2] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/khaliqgant/Projects/nango/feature/packages/worker/lib/worker.ts
[2]     at new NodeError (node:internal/errors:405:5)
[2]     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
[2]     at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
[2]     at defaultLoad (node:internal/modules/esm/load:101:20)
[2]     at nextLoad (node:internal/modules/esm/hooks:864:28)
[2]     at load (/Users/khaliqgant/Projects/nango/feature/node_modules/ts-node/dist/child/child-loader.js:19:122)
[2]     at nextLoad …
```
> Gh #1431 cleanup

- packages/jobs/lib/temporal.ts
- packages/worker/lib/worker.ts
Capping temporal worker  option `maxConcurrentWorkflowTaskExecutions` to 50. 
The goal is to make sure the number of concurrent sync/actions doesn't spike out of control. It might slow down syncs/actions but will give us some protection against sudden volume spike
https://linear.app/nango/issue/NAN-156/cap-concurrent-temporal-workflows
> temporal worker: set maxConcurrentWorkflowTaskExecutions to 50

- packages/jobs/lib/app.ts
- packages/jobs/lib/integration.service.ts
- packages/jobs/lib/runner/local.runner.ts
- packages/jobs/lib/runner/render.runner.ts
- packages/jobs/lib/runner/runner.ts
- packages/jobs/lib/temporal.ts
Creating a new runner instance on Render can be slow (> 60s). This PR introduces a fallback mechanism where jobs would fallback to the default runner if runner is not ready quickly. That allows to still create runner for each account dynamically but not wait for it to be ready in order to run the first sync(s). The account specific runner will be used in subsequent sync(s) once it is ready
this commit is also removing the global temporal flag for jobs service as well as the runner-for-account flag. Having full account isolation is worth the extra cost. Later in January we will work on a solution to bring runner cost down (suspending/resuming on demand for instance)
I have tested locally
> jobs: fallback to default runner if account runner is not ready quickly

- package-lock.json
- packages/jobs/package.json
- packages/server/package.json
it looks like v4.21.0 have introduced a memory leak. See https://github.com/DataDog/dd-trace-js/issues/3887 We are seeing some crash in nango-server due to
`RangeError: Maximum call stack size exceeded` error. Pinning dd-trace to 4.20.0 which doesn't seem to be affected by the memory leak until the problem is fixed
> pin dd-trace to 4.20.0

- package-lock.json
- packages/jobs/lib/client.ts
- packages/jobs/lib/server.ts
- packages/jobs/package.json
- packages/runner/lib/client.ts
- packages/runner/lib/client.unit.test.ts
- packages/runner/lib/server.ts
- packages/runner/package.json
using superjson as recommended on trpc documentation to ensure Dates are properly decoded.
Otherwise, trying to apply a date function to `nango.lastSyncDate` will throw an error since it would be considered a string
https://linear.app/nango/issue/NAN-186/nangolastsyncdate-gets-passed-as-string-instead-of-date
> fix: nangoProps lastSyncDate is not decoded as a Date

- packages/shared/lib/services/sync/data/data.service.ts
Postgress errors don't always have `detail` defined. ex:
This fix ensures the error displayed to end users doesn't contain `Detail: undefined` if no detail
https://linear.app/nango/issue/NAN-114/%5Bmarkprompt%5D-fix-error-message-for-batchsave-payload-size
> Hide postgress error internal details

- packages/shared/lib/models/Provider.ts
- packages/shared/lib/models/Proxy.ts
- packages/shared/lib/sdk/sync.ts
- packages/shared/lib/services/proxy.service.ts
- packages/shared/providers.yaml
Adds in retry header logic for Notion. Also allows runtime configuration for a retry header to be passed from a sync script
NAN-184
> [nan-184] add in notion retry header logic

- package-lock.json
- packages/jobs/lib/integration.service.ts
- packages/runner/lib/app.ts
- packages/runner/lib/client.ts
- packages/runner/lib/server.ts
- packages/runner/package.json
trpc is using undici fetch under the hood which has default timeout value of 300s. Therefore all mutation calls from jobs would fail after 5mins.
Overriding the fetch timeout options to disable any fetch timeouts 
Also adding a 24h timeout on the server side.
https://linear.app/nango/issue/NAN-199/fix-long-running-script
> fix: runner can run script for up to 24h

- .github/workflows/build-images.yaml
- .github/workflows/deploy.yaml
- .github/workflows/publish.yaml
- .github/workflows/push-container.yaml
I moved the deploy workflows in a subfolder at the last minute but that was a mistake. They must be at the root
> You must store workflow files in the .github/workflows directory of your repository.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows
> github action workflows cannot be in subfolder

- packages/server/lib/utils/utils.ts
- packages/server/lib/utils/utils.unit.test.ts
1. Updated `parseConnectionConfigParamsFromTemplate` to parse `proxy.base_url` in `/server/utils/utils.ts`.
2. Added test case for this in `/server/utils/utils.unit.test.ts`.
3. Tested locally if the `connectionConfigParams` has parsed `proxy.base_url` value in the response to the `ListIntegrations` request. 
4. Tested the presence of **Extra Configuration: {param}** textbox in the UI and executed proxy API call successfully.
fixes #1422
> Fixes Extra Configuration textbox missing

- package-lock.json
- package.json
- packages/cli/package.json
- packages/jobs/package.json
- packages/runner/package.json
- packages/server/package.json
- packages/shared/lib/services/sync/config/config.service.ts
- packages/shared/lib/services/sync/data/records.service.ts
- packages/shared/package.json
- scripts/publish.sh
- tsconfig.json
We are running into the following error when compiling individual package compare to using `npm run ts-build`:
> Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error
This seems to come from the fact that different packages uses diferrent version of typescript.
This PR aligns typescript version for all packages in the npm workspace, fixing errors caught by the compiler and ignore v5 warnings so all packages can be compiled individually or as a workspace
> fix 'importsNotUsedAsValues' deprecation error

- packages/shared/providers.yaml
Adds missing `refresh_params` to the `stripe-app` integration
> Adds missing grant type for stripe-app provider

- .github/workflows/push-container.yaml
Secrets are not available if github action workflow is triggered by a fork, making the container image push fail since logging into docker.hub cannot happen.
This commit ensure docker.hub login and image push doesn't occur if the pull request comes from a fork
> gh action: do not push imager if workflow running on fork

- .github/workflows/push-container.yaml
Attempt number 2 at not logging into docker.hub and not pushing container image if PR comes from a fork (since the secret credentials are not available for fork)
> Only push container images if PR or push from repo

- .github/workflows/push-container.yaml
My attempt number 2 at not pushing container when PR is coming from a non-collaborator has failed. :(
Instead of having a complicated condition to try to detect if container can be pushed, we now simply check if the secrets are available.
> push container workflow: don't push if docker secrets are not available

- .github/workflows/push-container.yaml
Attempt number 3456789 at preventing PR from external collaborators to fail because they cannot access repo secrets
fixing the if condition in the workflow
> fix: if condition in push container github action

- packages/jobs/lib/runner/local.runner.ts
- packages/jobs/lib/runner/render.runner.ts
- packages/jobs/lib/runner/runner.ts
- packages/shared/lib/index.ts
- packages/shared/lib/utils/metrics.manager.ts
First small step to make nango-jobs more resilient to Render downtime without compromising code execution isolation.
Before this change jobs would be hitting Render API to fetch Runner info and check it is running.
Job is now caching the runner and don't call Render on subsequent scripts if it already knows the runner.
It is also going to help with Render rate-limts as we grow.
Caveat: if Render is down, no new Runner would be created.
This change is also fixing a bug where when running locally each script will start a new runner process. Now same cached runner is being re-used
> jobs: caching runner

- package-lock.json
- packages/jobs/package.json
In the last npm publish autocommit, shared dependency was not updated to the latest version. Updating it manually
> fix: jobs should depends on shared v0.36.88

- package-lock.json
- packages/cli/package.json
- scripts/publish.sh
CLI should depends on shared 0.36.88
publish script: use explicit version instead of latest when updating dependencies
> CLI should depends on shared 0.36.88

- packages/frontend/lib/index.ts
- packages/frontend/lib/providers.ts
shopify login page set the `Cross-Origin-Opener-Policy: same-origin` header which prevents us to access attributes of the login window, in particular if the window was closed manually (window.closed is always true).
This commit introduces provider-based options where we can disable the login window closing detection per provider, otherwise nango.auth() would throw a `authorization window was closed before the authorization flow was completed` error
> frontend: disable login window detection when needed

- package-lock.json
- packages/cli/lib/services/local-integration.service.ts
- packages/cli/package.json
- packages/runner/lib/exec.ts
- packages/runner/package.json
Making zod available within scripts so customers can use it to validate data.
Note: customers would need to run `npm install zod` manually before they can `nango compile/deploy` scripts using zod
https://linear.app/nango/issue/NAN-230/[rumi]-support-zod-in-scripts
> Make zod available within script

- docs-v2/integrations/all/microsoft-tenant-specific.mdx
- docs-v2/sdks/frontend.mdx
- packages/frontend/lib/index.ts
- packages/frontend/lib/providers.ts
- packages/webapp/src/pages/AuthLink.tsx
The solution to disable closed auth window detection for shopify introduced in this PR is flawed. https://github.com/NangoHQ/nango/pull/1528
It relies on `providerConfigKey` which can be randomly set by the customer.
We discussed with @bastienbeurier and @rguldener about potential solutions to deal with this problem but they are all brittle and more complex. Given this is a very tiny feature of the Nango platform (and we have been spending a lot of time working on it), it has been decided to disable the automatic detection of closed auth page by default with an option for the customer to enable it if their workflow depends on it and the provider allows it
This is a breaking change and would require careful release and communication
> frontend: add option to auth() to enable closed window detection

- packages/server/lib/controllers/connection.controller.ts
Syncs were created twice when importing an API connection, this fixes that.
Fixes https://linear.app/nango/issue/NAN-254/[kula]-syncs-created-twice-when-importing-a-basic-auth-connection
> in most cases don't run the create connection hook

- docs-v2/spec.yaml
Updated property `description` on api-reference for the various endpoints; `/sync/trigger` , `/sync/start` and `/sync/pause`
The documentation update was reviewed using `npm run docs` and verifying on localhost.
> Fix docs on api-reference

- packages/shared/lib/sdk/sync.ts
- packages/shared/lib/services/proxy.service.ts
Turns out the update (https://github.com/NangoHQ/nango/pull/1527) throwing an error cancels the exponential backoff logic. This addition checks if we're attempting to retry and if so doesn't throw the error but rather returns it so the exponential back off / retry logic can kick in. Some of our larger customers rely heavily on the retry logic / parsing of headers so this is pretty important for them giving this fix some urgency.
NAN-258
> [nan-258] allow exponential backoffs to kick in for a proxy call

- packages/shared/lib/sdk/sync.ts
`nangoAction.updateMetadata` should allow to set any object not just strings
> sdk: fix type of the updateMetadata function

- docs-v2/sdks/node.mdx
- docs-v2/spec.yaml
- packages/node-client/lib/types.ts
- packages/shared/lib/models/Sync.ts
- packages/shared/lib/services/sync/orchestrator.service.ts
`GET /sync/status` now returns the effective frequency of the sync
> fix(api): /sync/status returns execution frequency

- packages/shared/lib/services/sync/sync.service.ts
- packages/webapp/src/pages/ConnectionDetails.tsx
- packages/webapp/src/types.ts
Displays the frequency in the connection's sync page, when you hover the next run.
Also displays if the frequency is not the default one (override).
> fix(ui): show frequency in connection's sync page

- packages/server/lib/controllers/webhook.controller.ts
- packages/shared/lib/integrations/scripts/webhook/github-app-oauth-webhook-routing.ts
- packages/shared/lib/integrations/scripts/webhook/github-app-webhook-routing.ts
- packages/shared/lib/integrations/scripts/webhook/hubspot-webhook-routing.ts
- packages/shared/lib/integrations/scripts/webhook/hubspot-webhook-routing.unit.test.ts
- packages/shared/lib/integrations/scripts/webhook/internal-nango.ts
- packages/shared/lib/integrations/scripts/webhook/jira-webhook-routing.ts
- packages/shared/lib/integrations/scripts/webhook/slack-webhook-routing.ts
- packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
- packages/shared/lib/utils/metrics.manager.ts
Webhoook cleanup and tracking. Refactored to move the `internal-nango` object code to its own file as it was semi confusing in which the order the code ran IMO
NAN-220
> [nan-220] move internal-nango outside for readability and track runtime via a metric

- packages/shared/lib/services/sync/config/deploy.service.ts
Follow up #1548 
When redeploying a sync the frequency used was the one from the yaml even if we had previously overrode the frequency via the API.
Now we fetch the value and use it if defined.
This is the only 2 places I could think of since I don't have all the knowledge, please tell me if there is any other place I should consider.
> fix(api): deploying sync now keeps frequency override

- packages/shared/lib/services/sync/orchestrator.service.ts
- packages/shared/lib/services/sync/schedule.service.ts
- packages/shared/lib/services/sync/sync.service.ts
There have been instances where the sync schedule gets out of step as provided by temporal. This can be due to double clicking in the UI or server issues. This updates the logic to resolve to what temporal says vs. our database in regards to the sync schedule. Also refactors to make the code more DRY
> [nan-208] trust temporal on sync schedule discrepencies

- packages/server/lib/controllers/config.controller.ts
We currently requires the instance_url config param to be fill in by the user in the connection creation script, even though the instance url is retrieve from the token response metadata.
This commit filter out any connection config param if it is also part of token response metadata
https://linear.app/nango/issue/NAN-259/[ninetailed]-salesforce-instance-url-should-not-be-a-mandatory
I have tested that providers like Salesforce, pipedrive or wildix-pbx don't show config param when creating a connection. Also verified providers like Freshdesk show the extra field
> proxy_url connection parameter config optional

- packages/persist/lib/controllers/persist.controller.ts
We currently only track the batchSave records size and count after writing to db was successful
It is most useful to always store this info regardless of the operation result
I noticed while investigating procurementScience issue with writing a ExternalBlobMetadata
> persist: always track records size/count, not just when writing was successful

- packages/shared/lib/services/sync/data/data.service.ts
Error 22001 is not related to row size but happens when trying to insert a string longer than the column's max size
https://www.postgresql.org/docs/current/errcodes-appendix.html
This is the error procurementScience is hitting. Probably because the model id is too long.
> fix: error detail for postgresql 22001 error

- packages/shared/lib/hooks/hooks.ts
Reported in the community that the call to the connection endpoint response is very slow on a hosted version
NAN-311
> [nan-311] don't attempt to start a sync if using hosted version

- packages/webapp/src/components/LeftNavBar.tsx
The version number is async loaded, since it is conditionally rendered it causes a flick at the bottom side of the left navbar:
I defaulted it to an `-` when the version is loading, getting rid of the flick above ☝️
> fix: webapp fix version flick

- package-lock.json
- packages/jobs/package.json
- packages/persist/package.json
- packages/server/lib/server.ts
- packages/server/package.json
- packages/shared/lib/utils/error.manager.ts
- packages/shared/package.json
Adding error in datadog APM automatically. 
Because of a "bug" in dd-trace, the errors are not reported automatically when used in express (cf: https://github.com/DataDog/dd-trace-js/issues/1944)
To resolve that we can tag the error manually. 
Fixes NAN-320
| before | after |
|--------|-------|
|    <img width="1344" alt="Screenshot 2024-02-05 at 15 21 07" src="https://github.com/NangoHQ/nango/assets/1637651/0ab9d8f8-a1af-4268-b362-ef0ba5772c90">    |  <img width="1354" alt="Screenshot 2024-02-05 at 15 20 54" src="https://github.com/NangoHQ/nango/assets/1637651/c3962bd0-5e14-4b0e-b055-822acffde1ea">     |
> fix(reporting): add error in datadog APM

- packages/server/lib/controllers/connection.controller.ts
- packages/server/lib/server.ts
- packages/shared/lib/services/connection.service.ts
- packages/webapp/src/pages/ConnectionList.tsx
- packages/webapp/src/utils/api.tsx
I added pagination to the connection list endpoint. With this, users can now either increment or decrement the connection list page using a specific offset and limit number. I also added the option to allow users to filter the connection list page by either `integration` or `connection`.
> Paginate list connections with filters

- packages/server/lib/controllers/connection.controller.ts
- packages/server/lib/server.ts
- packages/shared/lib/services/connection.service.ts
- packages/webapp/src/pages/ConnectionList.tsx
- packages/webapp/src/utils/api.tsx
This reverts commit 65821af7922c78d1a1b1fdaea8fd13c37fcaeaf5.
The commit changes the behavior of `listConnections(connectionId)`. It now returns entries for all connections regardless of the connection passed as param.
Reverting for now since it is impacting customers who are depending on the original behavior
https://nangohq.slack.com/archives/C06GHQPLTAN/p1707315634291829
> Revert "Paginate list connections with filters (#1573)"

- packages/server/lib/controllers/proxy.controller.ts
- packages/shared/lib/integrations/scripts/connection/connection.manager.ts
- packages/shared/lib/integrations/scripts/connection/github-app-oauth-post-connection.ts
- packages/shared/lib/integrations/scripts/connection/hubspot-post-connection.ts
- packages/shared/lib/integrations/scripts/connection/jira-post-connection.ts
- packages/shared/lib/integrations/scripts/connection/linear-post-connection.ts
- packages/shared/lib/integrations/scripts/webhook/github-app-oauth-webhook-routing.ts
- packages/shared/lib/models/Proxy.ts
- packages/shared/lib/sdk/sync.ts
- packages/shared/lib/sdk/sync.unit.test.ts
- packages/shared/lib/services/config.service.ts
- packages/shared/lib/services/proxy.service.ts
- packages/shared/lib/services/proxy.service.unit.test.ts
- packages/shared/lib/utils/error.ts
We don't want runners to have direct access to the database. The goal of this commit is to remove database dependency when calling the proxy service, while still executing the http request directly without going through our own API
This commit is refactoring the `proxyService.routeOrConfigure` function, splitting the function into 2 (`configure` and `route`, removing any db access within `configure` by passing all required data as inputs and returning the activity logs instead of writing them from within the function. Basically making the `configure` function side-effects free.
https://linear.app/nango/issue/NAN-291/call-to-nangoproxy-in-script-should-not-require-database-access-from
https://linear.app/nango/issue/NAN-282/[internal-tech-debt]-refactor-proxy-routeorconfigure-method
> refactor proxy service so proxying doesn't require access to db

- packages/shared/lib/sdk/sync.ts
Now that the sdk doesn't call createActivityLogMessage directly but send the log to persist API, the log message are not logged to the console anymore in the runner. This commit ensures activityLogs are also printed to the console
> sdk/sync: proxy should log to console

- packages/jobs/lib/runner/render.runner.ts
runners don't access the db directly anymore. Saving data is now done via the persist API
Left to do: remove the env vars for all existing runners
https://linear.app/nango/issue/NAN-292/remove-database-env-vars-from-the-runner
> remove db env vars for new runner

- packages/webapp/src/utils/language-snippets.tsx
Using a default instead of a named import leads to an error.
> Fix faulty Nango import for node in language-snippets util

- .dockerignore
Seems like I broke the docker image in #1651 
I thought we were compiling the code inside the docker image but looks like we are copying the dist after
> fix(docker): dist is not compiled in the docker image but copied

- packages/jobs/lib/crons/autoIdleDemo.ts
- packages/server/lib/jobs/index.ts
- packages/shared/lib/index.ts
I though the issue was the docker image but turns out there was an actual error. 
I will try to improve the CI to be able to catch this before hand (the current CI won't pass)
The error was `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/nango-server/src/node_modules/@nangohq/shared/lib/utils/metrics.manager'`
when running `docker run --platform linux/amd64 nangohq/nango-server:hosted`
```sh
docker build -f packages/server/Dockerfile . -t test --no-cache
docker run test
```
> fix: wrong export

- packages/server/lib/controllers/config.controller.ts
- packages/server/lib/utils/utils.ts
- packages/server/lib/utils/utils.unit.test.ts
parseConnectionConfigParamsFromTemplate: connection config parameters found in proxy attributes can be ignored if found in redirect_uri_metadata or token_response_metadata unless they are also in authorization_url or token_url 
Examples:
```
salesforce:
auth_mode: OAUTH2
authorization_url: https://login.salesforce.com/services/oauth2/authorize
token_url: https://login.salesforce.com/services/oauth2/token
token_response_metadata:
- instance_url
proxy:
base_url: ${connectionConfig.instance_url}
```
=> `${connectionConfig.instance_url}` can be ignored because it is returned within the token response metadata
```
wildix-pbx:
auth_mode: OAUTH2
authorization_url: https://${connectionConfig.subdomain}.wildixin.com/authorization/oauth2
token_url: …
```
> fix: connectionConfigParams parsing

- docker-compose.yaml
docker-compose for self-hosting should use `@nangohq/nango-server:hosted` tag
> docker-compose: use hosted tag for nango-server

- .github/workflows/build-images.yaml
- .github/workflows/push-container.yaml
Seems like GitHub is creating a fake commit hash when running pull-request CI, we were pushing orphan image but we were saved by the jobs running twice (once with the correct hash). 
I wish I could use `env` but it's not working with `uses` https://github.com/orgs/community/discussions/25246
> fix(ci): incorrect commit sha in PR

- .github/workflows/build-images.yaml
Third time's a charm.
Obviously it would be too easy if `github.event.pull_request.head.sha` were always there.
https://github.com/search?q=%22github.event.pull_request.head.sha+%7C%7C+github.sha%22&type=code 😭
> fix(ci): missing alternatives sha on master

- packages/webapp/src/pages/FlowCreate.tsx
The link in the embedded instructions for actions is broken (`actions` instead of the currently used `action`).
It might as well be instead that the guide url is incorrectly defined and that it is indeed supposed to be `actions`.
> Fix action guide link

- packages/cli/lib/fixtures/no-async-return.ts
- packages/cli/lib/services/parser.service.ts
- packages/cli/lib/sync.unit.test.ts
Fixes scenario where an action returns and complains about no awaiting
```
async function fetchAddress(nango: NangoSync, id: string) {
return nango.get({
endpoint: `/customer/${id}/addressBook`,
});
}
```
Triggers
```
nango.get() calls must be awaited in "./netsuite-customers-sync.ts:49". Not awaiting can lead to unexpected results.
```
> [nan-373] fix no return in an action and add test

- packages/jobs/lib/activities.ts
- packages/server/lib/controllers/appAuth.controller.ts
- packages/server/lib/controllers/oauth.controller.ts
- packages/server/lib/controllers/webhook.controller.ts
- packages/shared/lib/clients/sync.client.ts
- packages/shared/lib/hooks/hooks.ts
- packages/shared/lib/index.ts
- packages/shared/lib/integrations/scripts/connection/connection.manager.ts
- packages/shared/lib/integrations/scripts/webhook/internal-nango.ts
- packages/shared/lib/integrations/scripts/webhook/webhook.manager.ts
- packages/shared/lib/services/connection.service.ts
- packages/shared/lib/services/sync/config/deploy.service.ts
- packages/shared/lib/services/sync/data/records.service.ts
- packages/shared/lib/services/sync/run.service.ts
- packages/shared/lib/utils/telemetry.ts
- Proposing to rename metricsManager to Telemetry because it's doing log + metrics. 
Feel free to propose a new name or oppose this change
- Use dd-trace for metrics to avoid using the HTTP pool to send metrics
One "drawback" is that we no longer can't send the metrics definition, it should be done in the UI (which is standard practice but just wanted to warm)
- Renamed and split `captureMetric` to 3 different functions.
In Datadog you have multiple metrics types and we might at some point use more than just duration
- Renamed the Enums to fit their usage
- Removed the tags from metrics (namely `syncId` and `actionName` that could make the billing go up a lot)
Closes NAN-344
> feat(telemetry): use dd-trace for metrics

- packages/server/lib/controllers/activity.controller.ts
- packages/shared/lib/services/activity/activity.service.ts
- packages/webapp/src/pages/Activity.tsx
Integrations and connections filters now fetch from activities. Also fixed the issue where filtered result differs in `offset` value from the one requested to the server.
> feat(activity):connection and integration filters in activities

- packages/jobs/lib/temporal.ts
In case a backlog of Temporal activities forms we want jobs to be able to process more than 50 at a time
https://linear.app/nango/issue/NAN-389/increase-temporal-worker-max-concurrency-to-500
> Increase temporal worker max concurrency to 500

- packages/shared/lib/services/sync/run.service.ts
Fixes NAN-393
- The metric was also tracking action, Im not sure it was intended since there is a dedicated metric for that
- It wasnt tracking failure
> fix(datadog): incorrect metric for sync 

- packages/shared/providers.yaml
It seems that the authorization_url is not good for tiktok-accounts: https://business-api.tiktok.com/portal/docs?id=1766042058952706
> Update authorization_url for tiktok-accounts

- packages/jobs/lib/app.ts
- packages/jobs/lib/crons/autoIdleDemo.ts
- packages/jobs/lib/crons/deleteOldActivities.ts
- packages/server/lib/jobs/index.ts
- packages/server/lib/server.ts
- packages/shared/lib/services/activity/activity.service.ts
Following #1616 
Fixes NAN-394
Current clear was working but it was a naive implementation wrote quickly. We needed a long term fix that do not lock the table; especially in case where activityLogId would be > 10K messages.
Here we split the scripts to select/delete in batch:
- Select N log id
- Delete in small batch all the messages of this id
- Delete the log id
- Repeat
It's verbose on purpose because on production it's hard to know if something is locking or slow
> fix(cron): delete old activities safely

- packages/jobs/lib/index.ts
- packages/jobs/lib/tracer.ts
- packages/persist/lib/app.ts
- packages/persist/lib/server.ts
- packages/persist/lib/tracer.ts
- packages/runner/lib/app.ts
- packages/runner/lib/index.ts
We had a mixup in the tracer because jobs was loading the runner's tracer through a barrel file mistake (linter should have picked up missing `export types`).
- Add comments to barrel file to clarify expectation, not bulletproof but better than nothing
- Correctly load the tracer at the beginning of the entry points 
Note that it shouldn't be useful to load the tracer after it has been instantiated; since the config is global we could import `dd-trace` and avoid this mistake. 
- Remove `isCloud()` that was annoying locally
> fix(dd): correctly load tracer

- packages/jobs/lib/crons/deleteOldActivities.ts
- packages/shared/lib/utils/telemetry.ts
We are producing ~300k logs per day, the current pace is not enough to clear everything in a timely fashion
It's clear that we will need to rethink this table in a near future wether by using partition or by changing the storage entirely.
- Increase the pace
- Remove span that is too big to be sent to Datadog
> fix(cron): fine tune delete old activities

- packages/cli/lib/services/dryrun.service.ts
- packages/shared/lib/sdk/sync.ts
- packages/shared/lib/services/sync/run.service.ts
@bodinsamuel  noticed last week that when proxying/paginating we were making a call to `/config` to obtain the provider name (which mean that any nango.proxy call in scripts triggers 2 requests to our API, one to get connection credentials and one to get provider name) 
This PR is removing this request in favor of passing the provider as part of the NangoProps.
> sdk/sync: remove unecessary call to API (/config)

- package-lock.json
- packages/server/lib/controllers/ratelimit.middleware.ts
- packages/server/lib/server.ts
- packages/server/package.json
Add rate-limiting capabilities to server
https://linear.app/nango/issue/NAN-359/implement-rate-limiting
> server: rate limiter v1

- packages/jobs/lib/activities.ts
- packages/jobs/lib/workflows.ts
Set more appropriate timeout for temporal activities Faster timeout for actions and webhooks as well as setting scheduleToStart timeouts
Syncs: 1h enqueued, 24h to execute
Actions: 1m enqueued, 15mins to execute
Webhook: 1h enqueued, 15mins to execute
https://linear.app/nango/issue/NAN-388/[outage]-temporal-set-appropriate-timeouts-for-temporal-activities
> Fix: temporal activities timeout

- docs-v2/integrations/all/stripe-app.mdx
- packages/shared/providers.yaml
As it was, the stripe-app provider only worked for "External test" apps, and not for production apps (apps approved by Stripe).
This PR splits the provider into 2, adding a "stripe-app-sandox" provider, because the URL is formed differently in test and live.
Stripe-app docs are updated to reflect this change.
N/A
> Split stripe-app into 2 providers for live and sandbox

- packages/cli/lib/services/dryrun.service.ts
- packages/cli/lib/utils.ts
We cannot use the /sync/provider endpoint in CLI dryrun because the sync might have not be deployed yet and therefore doesn't exist.
> fix: use GET /config/KEY to obtain provider in cli dryrun

- packages/shared/lib/db/migrations/20240222135116_logs-index.cjs
Contributes to NAN-417
We are always ordering with the timestamp so it should make the default query faster. But because we have many filters it will be hard to optimize every queries. (in `getTopLevelLogByEnvironment()`) 
And it can take as much as 30s so it would help a lot.
I do wonder though Why `timestamp` is a `bigint`? It's weird and not optimized for time based filtering 
```sql
EXPLAIN ANALYZE SELECT
_nango_activity_logs.*
FROM
nango._nango_activity_logs
WHERE
environment_id = '3002' 
GROUP BY 
_nango_activity_logs.id
ORDER BY
_nango_activity_logs.timestamp DESC
LIMIT 100;
```
```sql
Limit  (cost=362484.08..362484.33 rows=100 width=202) (actual time=19250.301..19250.323 rows=100 loops=1)
->  Sort  (cost=362484.08..366085.24 rows=1440465 width=202) (actual …
```
> fix(db): add index for logs

- packages/shared/lib/db/migrations/20240222091347_sync-jobs-index.cjs
Fixes NAN-412
Impact two queries, not the slowest ones but executed quite often.
This index should make the query in prod go from average 60-100ms to 0-10ms, and obviously avoid the slow ones (currently topping a few seconds)
```sql
EXPLAIN ANALYSE SELECT
*
FROM
"nango"."_nango_sync_jobs"
WHERE
"sync_id" = 'aa037132-403f-465f-b9d4-5b7a21eadbd4'
AND "deleted" = FALSE
AND "type" = 'INITIAL'
AND "status" = 'RUNNING'
LIMIT 100;
```
```sql
Limit  (cost=162.77..165.01 rows=1 width=312) (actual time=94.953..94.956 rows=0 loops=1)
->  Bitmap Heap Scan on _nango_sync_jobs  (cost=162.77..165.01 rows=1 width=312) (actual time=94.952..94.954 rows=0 loops=1)
"        Recheck Cond: ((sync_id = 'd744f9ba-e823-42db-a3c2-22e905d2c2c7'::uuid) AND (status = 'RUNNING'::text))"
"        Filter: ((NOT deleted) …
```
> fix(db): add index for sync_jobs

- packages/shared/lib/db/migrations/20240222182357_configs-index.cjs
Every queries touching `_nango_configs` is using `where({ environment_id, deleted: false })`.
Current query plan filter out but we can improve this by using a partial index. None of them are slow but those are the most executed queries --after the logs.
Locally, from **0.1ms** to **0.04** (60% faster); in prod we can expect from 7ms to 3ms, it's a few minutes of CPU over a day because of the volume.
```sql
EXPLAIN ANALYZE SELECT
*
FROM
nango._nango_configs
WHERE
unique_key = 'test'
AND environment_id = 1
AND deleted = false;
```
```sql
Index Scan using _nango_configs_unique_key_environment_id_deleted_at_unique on _nango_configs  (cost=0.14..8.16 rows=1 width=3225) (actual time=0.030..0.031 rows=0 loops=1)
"  Index Cond: (((unique_key)::text = 'test'::text) AND (environment_id = 1))" …
```
> fix(db): add index to configs

- packages/server/lib/controllers/sync.controller.ts
- packages/shared/lib/utils/error.manager.ts
The function is not returning a NangoError but it was masked with the type casting.
The actual error that lead to this is yet to be fixed.
- Use generic error handling
- always put a default status just in case (it's the only place where we fully trusted the payload)
> fix(server): handle undefined status code

- packages/shared/lib/db/migrations/20240223150547_data_records-index.cjs
Fixes NAN-416
- The index created in #1719 was a just a test, it did work but it is not used enough to be worth the slowness it can create on write
- Create an index for `getAddedKeys()`.
This index allows the method to do an index only scan, meaning PG can reply without ever loading the table in memory.
Since it's called on `upsert()` it should make persist a bit faster.
Note that it's the same index as the unique key but for some reason it does not use it, maybe it's not stored the same way.
From **0.9ms** to **0.092 ms** (10x faster)
```sql
EXPLAIN ANALYZE SELECT
"external_id"
FROM
"nango"."_nango_sync_data_records"
WHERE
"nango_connection_id" = 2
AND "model" = 'GithubIssue'
AND "external_id" in('470723537', '385642199', '427035762');
```
```sql
Index Scan using …
```
> fix(db): add index for getAddedKeys()

- packages/shared/lib/db/migrations/20240223162238_connections-index.cjs
Almost all queries on `connection.service.ts` are using:
- `{ environment_id, deleted: false }`
OR
- `{ connection_id: connection.connection_id, provider_config_key: providerConfigKey, environment_id, deleted: false}`
OR
- `{ id, deleted: false }` (not relevant here)
The first one, even tho is the simplest, is also the slowest. 
Fixes NAN-434
- Add one index to fasten `listConnections()` and an other to fix almost all others queries.
I don't have enough connections locally to provide before and after, but I'm hopeful on 10x faster
```sql
Bitmap Heap Scan on _nango_connections  (cost=19.06..1341.77 rows=816 width=885) (actual time=0.449..2.843 rows=668 loops=1)
Recheck Cond: (environment_id = 835)
Filter: (NOT deleted)
Rows Removed by Filter: 781
Heap Blocks: exact=1167
->  Bitmap Index …
```
> fix(db): add index for connections

- packages/node-client/lib/index.ts
- packages/node-client/lib/types.ts
Fixes NAN-446
Node client was not exporting the types, making some comparison with enums impossible, and other stuff a bit annoying (pre-creating objects, reusing types in functions, etc...)
- Export all used types
> fix(node): expose all types

- packages/cli/lib/cli.ts
Fixes NAN-449
We were not ignoring ambient tsconfig when doing `nango dev` like we do on `nango deploy dev` 
- Skip project to avoid loading any `tsconfig.json`
- Do not redeclare a compiler each time we compile a file
> fix(cli): compiler should skip project

- package-lock.json
- packages/jobs/package.json
- packages/shared/lib/sdk/sync.ts
- packages/shared/lib/sdk/sync.unit.test.ts
Right now each call to `nango.proxy` in scripts makes a request to the api to fetch the connection.
This change caches the connection for 1 minute to avoid all those unnecessary api requests.
The `shouldRefreshCredentials` logic used in connection service is quite complex and requires accessing the database so we are not using it in the sdk but only cache the connection for one minute (happy to discuss this arbitrary value), which is good enough to avoid calling /connection/... on every proxy call without running into expired credentials
https://linear.app/nango/issue/NAN-411/reduce-the-number-of-calls-made-to-connection-when-proxying-from
> sdk proxy: memoize connection to avoid request on every proxy call

- packages/jobs/lib/crons/deleteSyncsData.ts
- packages/shared/lib/db/migrations/20240229220040_records_id-index.cjs
With the introduction of async delete in #1745 I noticed that the queries were taking a long time (+60sec), way too much for a select by id. Turns out we don't have an index on the primary key. 
(This could also help GET /records but not sure)
- Add unique index on pkey
- Still reduce the amount of deletion per loop because it could still take +10seconds
> fix(db): missing index on records

- packages/jobs/lib/runner/remote.runner.ts
- packages/jobs/lib/runner/runner.ts
- packages/shared/lib/services/file/remote.service.ts
* Add a remote instance runner so jobs doesn't need to spawn a process. In some cases I saw that a sync failed because spawning a process took too long. For enterprise customers they can setup a runner instance and so in that case jobs will connect to that remote instance instead. Customers can set this using the `RUNNER_SERVICE_URL` env variable
* Best practice is to use an AWS role for connecting to a bucket so this update allows customers to configure bucket connection using the role as long as they have `AWS_REGION` and `AWS_BUCKET_NAME` set
NAN-478
> [NAN-478] update runner logic to allow to connect to a remote instance

- packages/shared/lib/services/sync/data/records.service.ts
Records pagination should be based on `updated_at` instead of `created_at`
NAN-461
> [NAN-461] records pagination default ordering should be based on

- packages/webapp/src/pages/Connection/Syncs.tsx
In a multi model scenario the sync id will be the same so the dropdown might show more than once. Use a combination of the model return which has to be unique and the sync id to correctly identify the sync
NAN-439
> [nan-439] match syncs based on the sync id + model combo to prevent multiple dropdowns being open

- packages/webapp/src/pages/Connection/Authorization.tsx
Improve access token and refresh token fields to display a small message when refreshing tokens and update the values with the new tokens afterward. Revoked these displayed access tokens as well.
> feat(webapp):improve field values on refresh

- packages/shared/lib/db/database.ts
- packages/shared/lib/utils/retry.ts
- packages/shared/lib/utils/retry.unit.test.ts
In case multiple instances of server are trying to run migration at startup, knex lock mechanism can lead to one of the instance migration to fail and therefore fail to deploy.
In order to avoid failed migration because of lock, we wait and retry migrations
> retry db migrations

- packages/shared/lib/db/migrations/20240304130200_jobs-index-order.cjs
Fixes NAN-433
isSyncJobRunning() and getLatestSyncJob() both use an inefficient way to query the DB to avoid returning the wrong job in case of multiples are running (which needs to be fixed but we don't know why at the moment).
- Add an index to help both queries
It is a magnitude times faster, from **66s** to **0.5ms**
```sql
select * 
from _nango_sync_jobs 
where sync_id = '00831e7a-dce3-40c3-bce0-c5cf02d7b3a1' and deleted = FALSE 
order by created_at desc
LIMIT 1
```
```sql
Limit  (cost=0.43..555.70 rows=1 width=312) (actual time=66492.393..66492.394 rows=1 loops=1)
->  Index Scan Backward using _nango_sync_jobs_created_at_index on _nango_sync_jobs  (cost=0.43..746830.79 rows=1345 width=312) (actual time=66492.392..66492.393 rows=1 loops=1)
"        Filter: ((NOT deleted) AND (sync_id …
```
> fix(db): add index for isSyncJobRunning

- docs-v2/integrations/all/stripe-app.mdx
- packages/shared/lib/clients/provider.client.ts
- packages/webapp/public/images/template-logos/stripe-app-sandbox.svg
Nango was finding it hard to refresh `stripe-app`  access token upon expiration. This was because upon exchanging a code for an access token, there is no `expire_at` or `expire_in` value in the response. However, according to the [docs](https://docs.stripe.com/stripe-apps/api-authentication/oauth#refresh-access-token), the access token expires after an hour, which is equivalent to 3600 seconds. I added that value during the creation of the Stripe app token. This will help facilitate automatic refresh on access token expiration.
> fix(integration):stripe-app access token refresh on expire

- packages/webapp/src/utils/language-snippets.tsx
The name is misleading and previously was named to fit the getting started guide. Use a more appropriate name for the getting started and also the API Reference.
> [nan-439] fix improperly named const

- package-lock.json
- packages/shared/lib/services/sync/data/records.service.ts
- packages/shared/package.json
The main use of dayjs here was to make sure the timestamp is valid. If it is then use the timestamp passed in to maintain precision.
NAN-464
> [nan-464] fix precision issue

- packages/node-client/lib/index.ts
- packages/shared/lib/db/seeders/connection.seeder.ts
- packages/shared/lib/models/Sync.ts
- packages/shared/lib/services/sync/data/mocks.ts
- packages/shared/lib/services/sync/data/records.service.integration.test.ts
- packages/shared/lib/services/sync/data/records.service.ts
- packages/shared/lib/utils/encryption.manager.ts
Appending _nango_metadata to the record json in postgres tends to be slow when json is big
This commit remove the call to jsonb_set in the query and manipulate the json in js land to add _nango_metadata child attributes
https://linear.app/nango/issue/NAN-515/fetching-big-records-is-slow
> do not use jsonb_set in postgreSQL

- packages/shared/lib/services/sync/job.service.ts
Situation came up for two customers. One self hosted there was issues in their setup and so the initial sync didn't complete so was still in a running state. If an `INITIAL` sync has been running for more than 25 hours (1 hour grace period) then allow incremental syns to run since we can assume it is stuck
NAN-520
> [nan-520] if more than 25 hours then let the incremental sync run

- package-lock.json
- packages/shared/package.json
Fixes NAN-530
AWS upgraded their sdk with a broken version, it's usually better to have a `^` for libraries but in that case it's a side-effect and this library is not used by the CLI. Ultimately, the CLI should not import this package at all but in the meantime it's safer to pin back to something that was working.
- Pin dependency to last working version
> fix(deps): pin aws-sdk

- docs-v2/spec.yaml
- packages/server/lib/controllers/connection.controller.ts
- packages/shared/lib/utils/error.ts
A customer imported connections and didn't import the expiration date. Then one day the connections stopped working because the system never know when to refresh their access token. Unless a provider provides tokens that never expire force on import an expires_at or expires_in parameter
NAN-526
> [nan-526] for OAauth2 force an expiration unless explicitly stated

- docs-v2/integrate/guides/receive-webhooks-from-nango.mdx
- docs-v2/integrate/guides/sync-data-from-an-api.mdx
- packages/shared/lib/services/notification/webhook.service.ts
Since modifiedAfter is set at the beginning of the sync this value can always be used to fetch records. Update docs accordingly
NAN-532
> [NAN-532] Update docs because modifiedAfter isn't null for an initial sync

- packages/cli/lib/nango.yaml.schema.v2.json
- packages/server/lib/controllers/sync.controller.ts
- packages/shared/lib/services/sync/orchestrator.service.ts
- packages/shared/lib/services/sync/sync.service.ts
* Adds `track_deletes` to the nango.yaml schema
* Fixes issue with mismatch of the UI vs. the API when a sync is running
* Remove duplicated syncs when a connection id is passed to the status endpoint 
NAN-529
> [nan-529] fix bug in syncstatus endpoint

- packages/shared/lib/sdk/sync.integration.test.ts
- packages/shared/lib/sdk/sync.ts
See the community reported issue: https://nango-community.slack.com/archives/C04ABR352H0/p1710132351607969
The user is triggering an action from a sync in an effort to abstract out logic. This used to work until optional parameters were not allowed to be passed into a getConnection call with the changes in https://github.com/NangoHQ/nango/pull/1764/files#diff-f52f0d61cd6802499f5a31aca89d3aec3df278a751065390c02b6bbdb24c0840L337-R341
This update allows optional params to be passed into a getConnection call. The ideal case is that the caching of a connection call is keyed by a `providerConfigKey` and `connectionId` combination but I feel that is an edge case that is out of scope of the immediate user reported issue and this update resolves their blocking issue.
NAN-544
> [nan-544] allow optional params to be passed in and used

- packages/shared/lib/utils/utils.ts
- packages/shared/lib/utils/utils.unit.test.ts
* Support alias types that we support in models.service.ts
```
switch (field) {
case 'boolean':
case 'bool':
tsType = 'boolean';
break;
case 'string':
tsType = 'string';
break;
case 'char':
tsType = 'string';
break;
case 'integer':
case 'int':
case 'number':
tsType = 'number';
break;
case 'date':
tsType = 'Date';
break;
default:
tsType = field;
}
```
* Support array types
* Add tests to harden
> [nan-560] add tests and support array

- .env.example
- packages/shared/lib/services/sync/data/records.service.integration.test.ts
- packages/shared/lib/vitest.d.ts
- packages/shared/tsconfig.json
- tests/setupFiles.ts
- vite.integration.config.ts
Fixes NAN-593
- Add reusable helpers to vitest
> tests: add helpers to vitest

- packages/shared/lib/sdk/sync.ts
Allows a user to pass a generic to the ActionError, like so:
```
import type { NangoAction } from './models';
interface CustomError {
code: number;
key1: string;
}
export default async function runAction(nango: NangoAction): Promise<undefined> {
await nango.get({
baseUrlOverride: 'http://localhost:3009',
endpoint: '/'
});
const { ActionError } = nango;
throw new ActionError<CustomError>({
code: 12345,
key1: 'value1'
});
}
```
NAN-600
> [nan-600] pass in a generic

- packages/shared/lib/services/sync/data/delete.service.ts
I am a few days away from removing the records snapshot table but a customer is experiencing a sync failure in prod. so here is a quick fix to unblock the customer.
https://nangohq.slack.com/archives/C06FA6Q90BF/p1710782759958379
Deleting records (track_deletes=true) currently involves copying records from the snapshot table back into the records table. If there is a lot of records to copy, the query fails because the number of parameters goes beyond what's postgres supports, which I believe is 65k
Fixing this issue by inserting in chunks
https://linear.app/nango/issue/NAN-603/bug-deleting-too-many-records-track-deletes=true-results-in-an-error
I have reproduce the issue and tested the fix locally
> fix: deleting lots of records (track_deletes=true)

- packages/shared/lib/db/migrations/20240320184257_integration-unique-constraint-nulls-not-distinct.cjs
The unique constraint for integration is for unique_key, environment_id and deleted_at which can be null. However null values are not considered equal by default by postgres. 🤯 
from postgres doc at https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS
> By default, two null values are not considered equal in this
comparison. That means even in the presence of a unique constraint it is possible to store duplicate rows that contain a null value in at least one of the constrained columns. This behavior can be changed by adding the clause NULLS NOT DISTINCT
With this constraint, editing a integration with a name that already exists shows an error
https://linear.app/nango/issue/NAN-615/user-managed-to-create-two-integrations-with-the-same-integration-i …
> fix: integration should be unique per environment

- packages/shared/package.json
Follow up of #1887 
Obviously it wasn't going to be easy. For some reason changing the path also lead to npm not publishing the dist folder 
[0.39.5](https://www.npmjs.com/package/@nangohq/shared/v/0.39.5?activeTab=code) vs [0.39.6](https://www.npmjs.com/package/@nangohq/shared/v/0.39.6?activeTab=code)
- Explicitly list published files
> fix(shared): specify published files

- packages/cli/lib/cli.ts
- packages/cli/lib/services/compile.service.ts
- packages/cli/lib/services/compile.service.unit.test.ts
- packages/cli/lib/services/verification.service.ts
Followup of #1874 
When I did this eslint pass, I found undeclared usage of packages. It was the case for glob, so I had to pick a version. After testing, I picked the last one. 
While `nango cli dev` worked,  it turns out it had a slightly different logic than `nango deploy dev` which hide a change in behavior.
- Share a single unified way to listFiles
- Add tests
- npm run dw
- `node ../nango/packages/cli/dist/index.js dev`
- modify a sync
- `node ../nango/packages/cli/dist/index.js deploy dev`
- check that your file are still there and compiled
> fix(cli): glob change of behavior

- packages/shared/lib/services/sync/data/records.service.ts
Currently the record internal id is modified every time a record is updated which is counter intuitive and makes debugging harder
With this commit a record id is now a uuid v5 generated from the unique composite key (connection, model, external id)
> record id should not change between script executions

- packages/server/lib/controllers/auth.controller.ts
- packages/shared/lib/services/environment.service.ts
Fixes NAN-622
`getByEnvironmentName` is an unsafe function but until now it was only used outside cloud. During the deployment of the onboarding, I used this method to create the default provider without realising it wouldn't target the correct account.
- Enforce passing the accountId
- Other methods use their own stricter select
> fix(env): unsafe getEnvByName

- packages/server/lib/controllers/ratelimit.middleware.ts
Enabling rate-limiting (was only logging so far). 
Since I pushed the memoization of getConnection yesterday, no rate limiting has been logged so it should not impact anybody.
followup of https://github.com/NangoHQ/nango/pull/1708
> Enable server rate limit

- .eslintrc
- packages/server/lib/controllers/user.controller.ts
- packages/server/lib/index.ts
- packages/webapp/src/components/PrivateRoute.tsx
- packages/webapp/src/hooks/useUser.tsx
- packages/webapp/src/types.ts
- packages/webapp/src/utils/analytics.tsx
Fixes NAN-636
- Always call identify 
Some users are not identified correctly in PostHog. Looking at their session it seems that they didn't go through sign-in, so I might be due to the posthog cookie being deleted but not the nango session one. 
- Fix inconsistent types
- Catch export types error
> fix(ui): always identify to posthog

- packages/webapp/src/pages/InteractiveDemo/ActionBloc.tsx
- packages/webapp/src/pages/InteractiveDemo/AuthorizeBloc.tsx
- packages/webapp/src/pages/InteractiveDemo/DeployBloc.tsx
- packages/webapp/src/pages/InteractiveDemo/FetchBloc.tsx
- packages/webapp/src/pages/InteractiveDemo/index.tsx
Contributes to NAN-604
- Add more tracking on error and success
- Fix double loading of records
- Put a default title in the Action to avoid confusion
> fix(demo): feedbacks

- packages/shared/lib/services/sync/data/data.service.ts
- packages/shared/lib/services/sync/run.service.integration.test.ts
Sync can return incorrect deletion results. 
Fixing by getting directly getting the modified rows when `soft_delete = true`
https://linear.app/nango/issue/NAN-641/batchdelete-doesnt-return-the-correct-result
> fix: batchDelete returns incorrect sync result

- docs-v2/host/self-host/self-hosting-instructions.mdx
- docs-v2/reference/api/authentication.mdx
- docs-v2/reference/cli.mdx
- packages/cli/lib/cli.ts
- packages/cli/lib/index.ts
- packages/webapp/src/App.tsx
- packages/webapp/src/components/LeftNavBar.tsx
- packages/webapp/src/pages/EnvironmentSettings.tsx
- packages/webapp/src/pages/NotFound.tsx
- packages/webapp/src/pages/ProjectSettings.tsx
Fixes NAN-556
- Correct title and reference for environment settings
> fix(ui): environment settings title

- .env.example
- package-lock.json
- packages/utils/lib/environment/helpers.ts
- packages/utils/lib/environment/parse.ts
- packages/utils/lib/environment/parse.unit.test.ts
- packages/utils/package.json
Fixes NAN-662
Currently we are using `process.env` everywhere but it's untyped and always a pain to deal with `any`. The idea with this function is that each service can call it when they launch and combine it with their own set of required env vars. 
For example in logs I need Elasticsearch env but I can't make it globally required. (I'm sure it will be handy for @TBonnin too)
You can find an usage example here: https://github.com/NangoHQ/nango/blob/1085b3149239da8c2bd050fffc1021e39c34f061/packages/logs/lib/env.ts#L1-L4
The main drawback is that it can't be used for floating constants like we have in `detection.ts`. I guess **we need to decide** wether it's fine to have this function run directly or make the detection constants also an object in a function. I will say it's a bit less …
> fix(utils): parse env with zod

- packages/server/lib/controllers/onboarding.controller.ts
Tried to be smart about server side tracking because calls can be retried and some do not have dedicated endpoint (3 and 6), but some events are sent out of order making it hard to track on Posthog.
- Use more naive approach to server side tracking
> fix(demo): server side tracking

- .github/workflows/docker.yaml
- docker-compose.yaml
- packages/cli/docker/docker-compose.yaml
~I honestly don't know but seems to fix it.~
Also I realised I have pinned Postgres but if you are not part of this repo and do rely on the docker-compose.yml then it will scream at you that your data is not the same version as the docker image, so we have to leave those one as v16 unfortunately.
> fix(docker): change Postgres version for public docker-compose

- packages/jobs/lib/app.ts
- packages/jobs/lib/constants.ts
- packages/jobs/lib/runner/local.runner.ts
- packages/jobs/lib/runner/render.runner.ts
- packages/jobs/lib/server.ts
- packages/runner/lib/monitor.ts
- packages/runner/lib/server.ts
- packages/shared/lib/utils/utils.ts
- packages/utils/lib/environment/parse.ts
The goal is to report the runner high memory usage so users can understand better when a script is failing.
This is not a perfect solution, for example if memory spikes and runner crashes within a check interval no activity log would be emitted.
@bastienbeurier this is how it looks like
https://linear.app/nango/issue/NAN-665/make-runner-out-of-memory-error-more-explicit
> runner: report high memory usage

- .github/workflows/cli-verification.yaml
- scripts/publish.sh
The goal with this PR is to mimic a publish process of the cli with the code that is in review to ensure a working cli that is in a remote source. This is accomplished by building and publishing the packages to the Github registry and finally using the cli to verify that it works expected. This will protect against instances where a faulty cli is published. This will be especially useful to verify that this PR: https://github.com/NangoHQ/nango/pull/1918 works as expected with packaging the utils package. Additionally, as we refactor the cli to move code out of shared and reduce the package size of the cli this will ensure things still work as expected.
NAN-668
> [nan-668] add verification bash script to publish packages

- packages/runner/lib/monitor.ts
Introduced a bug in https://github.com/NangoHQ/nango/pull/1943/files which cause runner with max idle time set to zero like the default runner or paying customer to idle all the time.
> fix: do not idle runner if idleMaxDurationMs is 0

- packages/server/lib/controllers/sync.controller.ts
Fixes NAN-690
- Correctly await verifyOwnership
- Add missing return after response code
- Reuse activityLogId
> fix(sync): verifyOwnership not awaited

- packages/cli/lib/templates/action.ejs
- packages/jobs/lib/runner/local.runner.ts
- packages/runner/lib/exec.ts
- packages/shared/lib/sdk/sync.ts
- packages/shared/lib/services/environment.service.ts
This allows a user to have a coordinating action that tells sync when to start based on input from other syncs. As a proof of concept example:
- coordinating action
```
import type { NangoAction } from './models';
export default async function runAction(nango: NangoAction, input?: string): Promise<boolean> {
await nango.log('starting action');
await nango.log(input);
const order = [
'first-sync',
'second-sync'
];
if (!input && order[0] && typeof order[0] === 'string') {
await nango.log('running first sync');
await nango.triggerSync(nango.providerConfigKey, nango.connectionId, order[0] as string)
} else {
if (!order.includes(input as string)) {
throw new Error(`Invalid input: ${input}`);
}
const index = order.indexOf(input as string);
const nextIndex = index + 1;
if (order[nextIndex] && …
```
> [NAN-698] Add the ability to call a sync from an action

- packages/shared/providers.yaml
Fixing Wave Accounting configuration
Exchange code with url https://api.waveapps.com/oauth2/token - 405
Exchange the same code with url https://api.waveapps.com/oauth2/token/ - 200
> fix wave accounting token url

- package-lock.json
- packages/shared/package.json
undici version was bumped yesterday but the sentry lib version 7.105 doesn't support it. Bumping sentry to 7.106 where the issue was fixed.
https://github.com/getsentry/sentry-javascript/releases/tag/7.106.0 
https://github.com/getsentry/sentry-javascript/pull/10938
> fix: TypeError: request.headers.split is not a function

- packages/server/lib/controllers/sync.controller.ts
logs in render don't show extra info like environment, connectionId, etc... which makes it harder to debug
tested locally
> fix: logs don't show the context when detecting records differences

- packages/server/lib/controllers/onboarding.controller.ts
- packages/server/lib/controllers/sync.controller.ts
I won't merge this PR today, monitoring the fetch and compare logs for now but I will appreciate a review.
It is behind a feature flag anyway.
Returns records from the new database if flag is enabled (`new-records-return:global`)
> records migration: return records from new database

- packages/records/lib/models/records.integration.test.ts
- packages/records/lib/models/records.ts
- packages/shared/lib/services/sync/data/data.service.ts
Upsert summary would count already deleted records or non-existing ones as deleted
https://linear.app/nango/issue/NAN-727/sync-logs-always-return-all-deleted-records-even-when-they-were
Tested locally
> fix: batchDelete counts already deleted records or non-existing ones as deleted

- packages/shared/lib/services/connection.service.ts
- packages/shared/lib/services/sync/sync.service.ts
Fixes NAN-776
Page `http://localhost:3000/dev/connections/<Integration>/<id>` was sometimes showing foreign models in the table. After investigating it seems we were joining on name which matched random data on the table.
- Fix join by using sub-select 
Not entirely sure what was the expected output for multi model sync (cf: screenshot) but seems correct like this, (tbh I find this view quite confusing)
- Bonus: missing `config_id` for new unauthenticated connection 
---
> fix(api): wrong join for getSyncs

- docker-compose.yaml
fix #2035
If not env var is not set, it defaults to localhost anyway
https://linear.app/nango/issue/NAN-784/invalid-interpolation-format-for-records-string-and-connection-refused
Tested `docker compose` up locally
> do not interpolate RECORDS_DATABASE_URL in docker compose

- package.json
- packages/server/lib/server.ts
- packages/webapp/src/App.tsx
- packages/webapp/src/components/TopNavBar.tsx
- packages/webapp/src/pages/HNDemo.tsx
fixes NAN-788
- Introduce a temporary frontend endpoint to automatically create an account and redirect to the interactive demo. 
It detects if we are connected to avoid creating new accounts for nothing otherwise it will create an account with a random id and email `demo-<id>@example.com`.
- Banner is displayed when connected to a demo account 
- Bonus: fix the broken script to compile
---
> feat: hn demo

- packages/records/lib/db/config.ts
- packages/records/lib/models/records.ts
Contributes to NAN-796
There is discrepancy is the new records storage, we have a lot of error in production related to pool exhaustion which is probably due do the fact that the transactions were not reusing the connection correctly.  Not entirely sure it's the full fix but maybe
- Fix transaction usage
- Still increase the pool since we have a better DB
```logs
2024-04-25T08:58:41.431Z [ERROR] [records] Failed to upsert records to table records.
Model: ***, Nango Connection ID: ***.
Attempted to insert/update/delete: 100 records
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
2024-04-25T08:58:41.431Z [ERROR] [PersistController] Failed to save records: Error: Failed to upsert records to table records.
```
> fix(records): transaction not reusing opened connection

- packages/server/lib/controllers/onboarding.controller.ts
- packages/server/lib/controllers/sync.controller.ts
- packages/shared/lib/services/sync/orchestrator.service.ts
- Fix missing logContextGetter in SyncCommand
It wasn't caught by TS because connection_id is `any`. Took the opportunity to move to a json object, this is handy and also prevent more of this kind of errors
> fix(logs): missing contextGetter in syncCommand

- packages/jobs/lib/tracer.ts
- packages/persist/lib/tracer.ts
- packages/server/lib/tracer.ts
Making the ddtrace pg.service depend on the database name in order to be able to differentiate apm metrics between main and records dbs. ex: `postgres-nango_tbvo` or `postgres-records`
https://datadoghq.dev/dd-trace-js/interfaces/export_.plugins.pg.html#service
Note: requires changing the DD dashboard db widget
https://linear.app/nango/issue/NAN-746/datadog-apm-graphs-for-records-db-datadog-database-monitoring
> dynamic ddtrace pg.service 

- packages/cli/lib/index.ts
- packages/cli/lib/services/migration.service.ts
- packages/cli/lib/services/verification.service.ts
- packages/logs/lib/es/helpers.ts
Adds a cli migration command `nango migrate-to-directories` to easily change to the nested cli directory structure
NAN-751
> [NAN-751] Add migrate command to make migration easier

- packages/records/lib/models/records.ts
- packages/shared/lib/db/database.ts
- packages/utils/lib/index.ts
- packages/utils/lib/retry.ts
- packages/utils/lib/retry.unit.test.ts
Postgres doc advises to retry deadlock failures
https://www.postgresql.org/docs/current/mvcc-serialization-failure-handling.html
This commit also moves `retry` to `packages/utils`
Tested Locally
> retry deadlock_detected error when upserting records
